import type { TimetableSession } from "./types";

export const TIMETABLE_SEED_SESSIONS: TimetableSession[] = [
  {
    id: "seed-tai-chi-tue",
    title: "Tai Chi",
    style: "tai-chi",
    dayOfWeek: 1,
    slotId: "slot-1830-1930",
    cancelledDates: [],
  },
  {
    id: "seed-contemporary-tue",
    title: "Contemporary Dance",
    style: "contemporary",
    dayOfWeek: 1,
    slotId: "slot-1930-2040",
    cancelledDates: [],
  },
  {
    id: "seed-yoga-gentle-wed",
    title: "Yoga (Gentle Flow)",
    style: "yoga",
    dayOfWeek: 2,
    slotId: "slot-1830-1920",
    level: "Gentle Flow",
    cancelledDates: [],
  },
  {
    id: "seed-tango-beginner-wed",
    title: "Tango (Beginner)",
    style: "tango",
    dayOfWeek: 2,
    slotId: "slot-1930-2030",
    level: "Beginner",
    cancelledDates: [],
  },
  {
    id: "seed-tango-intermediate-wed",
    title: "Tango (Intermediate)",
    style: "tango",
    dayOfWeek: 2,
    slotId: "slot-2030-2130",
    level: "Intermediate",
    cancelledDates: [],
  },
  {
    id: "seed-chinese-class-1-thu",
    title: "Chinese Dance Class 1 (Classical Dance Performance)",
    style: "chinese-dance",
    dayOfWeek: 3,
    slotId: "slot-1830-2000",
    level: "Classical Dance Performance",
    cancelledDates: [],
  },
  {
    id: "seed-chinese-class-2-thu",
    title: "Chinese Dance Class 2 (Soft Training)",
    style: "chinese-dance",
    dayOfWeek: 3,
    slotId: "slot-2000-2130",
    level: "Soft Training",
    cancelledDates: [],
  },
  {
    id: "seed-yoga-vinyasa-fri",
    title: "Yoga (Vinyasa Flow)",
    style: "yoga",
    dayOfWeek: 4,
    slotId: "slot-1830-1920",
    level: "Vinyasa Flow",
    cancelledDates: [],
  },
  {
    id: "seed-tango-advanced-sat",
    title: "Tango (Advanced)",
    style: "tango",
    dayOfWeek: 5,
    slotId: "slot-1900-2000",
    level: "Advanced",
    cancelledDates: [],
  },
  {
    id: "seed-tango-practice-sat",
    title: "Tango (Practice)",
    style: "tango",
    dayOfWeek: 5,
    slotId: "slot-2000-2130",
    level: "Practice",
    cancelledDates: [],
  },
  {
    id: "seed-yoga-inside-sat",
    title: "Yoga (Inside Flow)",
    style: "yoga",
    dayOfWeek: 5,
    slotId: "slot-1530-1700",
    level: "Inside Flow",
    cancelledDates: [],
  },
];
