import type { TimetableSession } from "./types";

export const TIMETABLE_SEED_SESSIONS: TimetableSession[] = [
  {
    id: "seed-contemporary-mon",
    title: "Contemporary — Open Level",
    style: "contemporary",
    dayOfWeek: 0,
    slotId: "slot-4",
    instructor: "Sophie",
    level: "Open",
    cancelledDates: [],
  },
  {
    id: "seed-chinese-tue",
    title: "Chinese Dance — Beginners",
    style: "chinese-dance",
    dayOfWeek: 1,
    slotId: "slot-5",
    instructor: "Kiki",
    level: "Beginner",
    cancelledDates: [],
  },
  {
    id: "seed-yoga-wed",
    title: "Yoga Flow",
    style: "yoga",
    dayOfWeek: 2,
    slotId: "slot-1",
    instructor: "Eleanor",
    level: "All levels",
    cancelledDates: [],
  },
  {
    id: "seed-tango-thu",
    title: "Tango — Improvers",
    style: "tango",
    dayOfWeek: 3,
    slotId: "slot-6",
    instructor: "Marcus",
    level: "Intermediate",
    cancelledDates: [],
  },
  {
    id: "seed-tai-chi-fri",
    title: "Tai Chi",
    style: "tai-chi",
    dayOfWeek: 4,
    slotId: "slot-2",
    instructor: "Michael",
    level: "Open",
    cancelledDates: [],
  },
  {
    id: "seed-contemporary-sat",
    title: "Contemporary — Beginners",
    style: "contemporary",
    dayOfWeek: 5,
    slotId: "slot-2",
    instructor: "Sophie",
    level: "Beginner",
    cancelledDates: [],
  },
  {
    id: "seed-yoga-sun",
    title: "Sunday Yoga",
    style: "yoga",
    dayOfWeek: 6,
    slotId: "slot-3",
    instructor: "Eleanor",
    level: "All levels",
    cancelledDates: [],
  },
];
