/** Auto-generated from site.source.ts — edit content/website-copy.csv then run: npm run content:import */

export const copy = {
  "global.footer.columns.explore.links.classes.label": "Classes",
  "global.footer.columns.explore.links.courses.label": "Courses",
  "global.footer.columns.explore.links.events.label": "Events",
  "global.footer.columns.explore.links.faq.label": "FAQ",
  "global.footer.columns.explore.links.gift_cards.label": "Gift Cards",
  "global.footer.columns.explore.title": "Explore",
  "global.footer.columns.school.links.about_us.label": "About Us",
  "global.footer.columns.school.links.careers.label": "Careers",
  "global.footer.columns.school.links.our_faculty.label": "Our Faculty",
  "global.footer.columns.school.links.private_events.label": "Private Events",
  "global.footer.columns.school.title": "The School",
  "global.footer.contact.address.0": "2nd Floor, County Hall Main Entrance",
  "global.footer.contact.address.1": "Belvedere Road",
  "global.footer.contact.address.2": "London SE1 7PB",
  "global.footer.contact.email": "info@countyhalldancecentre.com",
  "global.footer.contact.phone": "+44 7728 617531",
  "global.footer.contact.title": "Visit Us",
  "global.footer.contact.wechat": "WeChat: 18518614868",
  "global.footer.copyright": "© {year} County Hall Dance & Performing Arts School. All rights reserved.",
  "global.footer.intro": "A home for dance, movement and creativity at County Hall on the South Bank. Move. Create. Connect. Belong.",
  "global.footer.legal.cookie_policy.label": "Cookie Policy",
  "global.footer.legal.privacy_policy.label": "Privacy Policy",
  "global.footer.legal.safeguarding.label": "Safeguarding",
  "global.footer.legal.terms_conditions.label": "Terms & Conditions",
  "global.footer.newsletter.description": "Occasional news on classes, masterclasses, and performances.",
  "global.footer.newsletter.placeholder": "Your email address",
  "global.footer.newsletter.submitlabel": "Subscribe",
  "global.footer.newsletter.title": "Stay in touch",
  "global.logo.alt": "County Hall Dance & Performing Arts School",
  "global.logo.nameline1": "County Hall",
  "global.logo.nameline2": "Dance & Performing Arts School",
  "global.navigation.booktrial.label": "Book a Trial",
  "global.navigation.items.about_us.children.about_us.label": "About Us",
  "global.navigation.items.about_us.children.contact.label": "Contact",
  "global.navigation.items.about_us.children.faqs.label": "FAQs",
  "global.navigation.items.about_us.children.gift_cards.label": "Gift Cards",
  "global.navigation.items.about_us.children.join_us.label": "Join Us",
  "global.navigation.items.about_us.children.membership_terms.label": "Membership Terms",
  "global.navigation.items.about_us.label": "About Us",
  "global.navigation.items.classes.children.booking.label": "Booking",
  "global.navigation.items.classes.children.class_descriptions.label": "Class Descriptions",
  "global.navigation.items.classes.children.instructors.label": "Instructors",
  "global.navigation.items.classes.children.taster_classes.label": "Taster Classes",
  "global.navigation.items.classes.children.timetable.label": "Timetable",
  "global.navigation.items.classes.label": "Classes",
  "global.navigation.items.events.children.cross_arts_events.label": "Cross-Arts Events",
  "global.navigation.items.events.children.masterclasses.label": "Masterclasses",
  "global.navigation.items.events.children.milonga.label": "Milonga",
  "global.navigation.items.events.children.performances.label": "Performances",
  "global.navigation.items.events.children.social_dance_nights.label": "Social Dance Nights",
  "global.navigation.items.events.children.workshops.label": "Workshops",
  "global.navigation.items.events.label": "Events",
  "global.navigation.items.membership.children.booking_access.label": "Booking Access",
  "global.navigation.items.membership.children.member_benefits.label": "Member Benefits",
  "global.navigation.items.membership.children.monthly_passes.label": "Monthly Passes",
  "global.navigation.items.membership.label": "Membership",
  "global.navigation.items.private_lessons.children.corporate_events.label": "Corporate Events",
  "global.navigation.items.private_lessons.children.couples_dance.label": "Couples' Dance",
  "global.navigation.items.private_lessons.children.first_wedding_dance.label": "First Wedding Dance",
  "global.navigation.items.private_lessons.children.group_experiences.label": "Group Experiences",
  "global.navigation.items.private_lessons.children.one_to_one_lessons.label": "One-to-One Lessons",
  "global.navigation.items.private_lessons.children.school_organisation_workshops.label": "School / Organisation Workshops",
  "global.navigation.items.private_lessons.label": "Private Lessons",
  "global.navigation.items.shop.children.accessories.label": "Accessories",
  "global.navigation.items.shop.children.county_hall_merchandise.label": "County Hall Merchandise",
  "global.navigation.items.shop.children.dancewear.label": "Dancewear",
  "global.navigation.items.shop.children.t_shirts.label": "T-Shirts",
  "global.navigation.items.shop.label": "Shop",
  "global.navigation.items.studio_hire.children.our_space.label": "Our Space",
  "global.navigation.items.studio_hire.children.space_booking.label": "Space Booking",
  "global.navigation.items.studio_hire.label": "Studio Hire",
  "global.navigation.search.label": "Search",
  "global.navigation.search.placeholder": "Search classes, courses, events…",
  "global.utilitybar.email.label": "info@countyhalldancecentre.com",
  "global.utilitybar.findus.label": "Find us",
  "global.utilitybar.phone.label": "+44 7728 617531",
  "global.utilitybar.social.facebook.label": "Follow us on Facebook",
  "global.utilitybar.social.instagram.label": "@countyhalldancecentre",
  "global.utilitybar.social.youtube.label": "Watch us on YouTube",
  "home.aboutteaser.body.0": "Founded at the historic County Hall, our school brings together rigorous technical training and a deeply supportive community.",
  "home.aboutteaser.body.1": "Whether you are taking your first plié or preparing for vocational study, our faculty guides every student with patience and precision.",
  "home.aboutteaser.cta.label": "About the school",
  "home.aboutteaser.image.alt": "Students and teachers in the County Hall studio corridor",
  "home.aboutteaser.overline": "Our story",
  "home.aboutteaser.title": "Rooted in London, reaching for excellence",
  "home.classstyles.items.chinese_dance.image.alt": "Chinese dance class",
  "home.classstyles.items.chinese_dance.name": "Chinese Dance",
  "home.classstyles.items.contemporary.image.alt": "Contemporary dance class",
  "home.classstyles.items.contemporary.name": "Contemporary",
  "home.classstyles.items.k_pop.image.alt": "K-Pop dance class",
  "home.classstyles.items.k_pop.name": "K-Pop",
  "home.classstyles.items.tai_chi.image.alt": "Tai Chi class",
  "home.classstyles.items.tai_chi.name": "Tai Chi",
  "home.classstyles.items.tango.image.alt": "Tango class",
  "home.classstyles.items.tango.name": "Tango",
  "home.classstyles.items.yoga.image.alt": "Yoga class",
  "home.classstyles.items.yoga.name": "Yoga",
  "home.classstyles.overline": "Our disciplines",
  "home.classstyles.subtitle": "Adult classes in Contemporary, Chinese Dance, Tango, Yoga, Tai Chi and K-Pop — beginners welcome.",
  "home.classstyles.title": "Class styles",
  "home.events.items.contemporary_intensive_maya_chen.booknow.label": "Book Now",
  "home.events.items.contemporary_intensive_maya_chen.date": "Saturday 18 October 2026",
  "home.events.items.contemporary_intensive_maya_chen.image.alt": "Contemporary dance intensive workshop",
  "home.events.items.contemporary_intensive_maya_chen.location": "Studio A",
  "home.events.items.contemporary_intensive_maya_chen.title": "Contemporary Intensive with Maya Chen",
  "home.events.items.junior_ballet_masterclass.booknow.label": "Book Now",
  "home.events.items.junior_ballet_masterclass.date": "Sunday 26 October 2026",
  "home.events.items.junior_ballet_masterclass.image.alt": "Junior ballet masterclass in progress",
  "home.events.items.junior_ballet_masterclass.location": "Studio B",
  "home.events.items.junior_ballet_masterclass.title": "Junior Ballet Masterclass",
  "home.events.items.musical_theatre_workshop_day.booknow.label": "Book Now",
  "home.events.items.musical_theatre_workshop_day.date": "Saturday 8 November 2026",
  "home.events.items.musical_theatre_workshop_day.image.alt": "Musical theatre workshop participants on stage",
  "home.events.items.musical_theatre_workshop_day.location": "Main Hall",
  "home.events.items.musical_theatre_workshop_day.title": "Musical Theatre Workshop Day",
  "home.events.items.winter_showcase.booknow.label": "Book Now",
  "home.events.items.winter_showcase.date": "Friday 12 December 2026",
  "home.events.items.winter_showcase.image.alt": "Winter showcase performance lighting",
  "home.events.items.winter_showcase.location": "County Hall Theatre",
  "home.events.items.winter_showcase.title": "Winter Showcase — Tickets On Sale",
  "home.events.overline": "What's on",
  "home.events.title": "Upcoming masterclasses & events",
  "home.events.viewall.label": "View all events",
  "home.hero.nextlabel": "Next",
  "home.hero.previouslabel": "Previous",
  "home.hero.slides.hero_classes.blurb": "Explore adult classes in Contemporary, Chinese Dance, Tango, Yoga and Tai Chi.",
  "home.hero.slides.hero_classes.cta.label": "View Classes",
  "home.hero.slides.hero_classes.headline": "Classes",
  "home.hero.slides.hero_classes.image.alt": "Couple performing Argentine tango on an outdoor dance floor",
  "home.hero.slides.hero_events.blurb": "Milongas, themed social nights, masterclasses and cross-arts events.",
  "home.hero.slides.hero_events.cta.label": "View Events",
  "home.hero.slides.hero_events.headline": "Events",
  "home.hero.slides.hero_events.image.alt": "Contemporary dancers in a bright studio with ballet barres",
  "home.hero.slides.hero_intro.blurb": "Dance, movement and creative experiences at London's iconic County Hall on the South Bank — classes, workshops and events for adults of every background and level of experience.",
  "home.hero.slides.hero_intro.cta.label": "Explore Classes",
  "home.hero.slides.hero_intro.headline": "Discover dance, movement and creative experiences at London's iconic County Hall.",
  "home.hero.slides.hero_intro.image.alt": "Dancers taking a bow after an outdoor performance on the South Bank",
  "home.hero.slides.hero_membership.blurb": "A more flexible way to keep dancing, join events and belong to the community.",
  "home.hero.slides.hero_membership.cta.label": "Membership",
  "home.hero.slides.hero_membership.headline": "Membership",
  "home.hero.slides.hero_membership.image.alt": "Group dance class in a sunlit studio",
  "home.hero.slides.hero_private_lessons.blurb": "Tailored sessions for individuals, couples, wedding first dances and small groups.",
  "home.hero.slides.hero_private_lessons.cta.label": "Enquire",
  "home.hero.slides.hero_private_lessons.headline": "Private Lessons & Experiences",
  "home.hero.slides.hero_private_lessons.image.alt": "Instructor guiding a student in a one-to-one dance session",
  "home.hero.slides.hero_studio_hire.blurb": "A South Bank space for dance, theatre and film rehearsals, castings, workshops and events.",
  "home.hero.slides.hero_studio_hire.cta.label": "Studio Hire",
  "home.hero.slides.hero_studio_hire.headline": "Studio Hire",
  "home.hero.slides.hero_studio_hire.image.alt": "Outdoor community dance performance with audience on the South Bank",
  "home.newsletter.description": "Follow our journey and receive curated updates on classes, performances, and exclusive offers.",
  "home.newsletter.overline": "Join our circle",
  "home.newsletter.placeholder": "Email address",
  "home.newsletter.socialheading": "Connect with us",
  "home.newsletter.submitlabel": "Sign up",
  "home.newsletter.title": "Newsletter & social",
  "home.privateevents.body": "Host an unforgettable birthday, hen party, or team celebration in our beautiful studios. Choose a theme, bring your guests, and leave the choreography to us.",
  "home.privateevents.cta.label": "Enquire",
  "home.privateevents.image.alt": "Private dance party celebration in studio",
  "home.privateevents.overline": "Celebrate with us",
  "home.privateevents.title": "Private events & parties",
  "home.quickactions.items.book_a_class.description": "See the weekly timetable and reserve your place.",
  "home.quickactions.items.book_a_class.label": "Book a Class",
  "home.quickactions.items.hire_the_studio.description": "Two flexible spaces at County Hall, from £200 per hour.",
  "home.quickactions.items.hire_the_studio.label": "Hire the Studio",
  "home.quickactions.items.join_now.description": "Become a member and enjoy monthly, quarterly or annual plans with exclusive benefits.",
  "home.quickactions.items.join_now.label": "Join Now",
  "home.quickactions.linksuffix": "Learn more →",
  "home.quickactions.overline": "Get started",
  "meta.defaultdescription": "Adult dance and movement classes at London's iconic County Hall on the South Bank — Contemporary, Chinese Dance, Tango, Yoga, Tai Chi and K-Pop, plus workshops, private lessons and studio hire.",
  "meta.shortname": "CHD PAS",
  "meta.sitename": "County Hall Dance & Performing Arts School",
  "pages.about.cta.body": "We would love to welcome you for a trial class or a tour of the studios.",
  "pages.about.cta.button.label": "Get in touch",
  "pages.about.cta.title": "Visit us",
  "pages.about.faculty.intro": "Our teachers are working artists and experienced educators, selected for both technical expertise and pastoral care.",
  "pages.about.faculty.members.faculty_kiki.bio": "A highly experienced choreographer and large-scale performance director, Kiki shapes the Centre's artistic programme and its connection between dance, music, visual art and culture.",
  "pages.about.faculty.members.faculty_kiki.image.alt": "Kiki",
  "pages.about.faculty.members.faculty_kiki.name": "Kiki",
  "pages.about.faculty.members.faculty_kiki.role": "Company Director and Artistic Director",
  "pages.about.faculty.members.faculty_michael.bio": "Michael brings extensive international film, television and production-management experience, leading operations, partnerships, communications and business development.",
  "pages.about.faculty.members.faculty_michael.image.alt": "Michael",
  "pages.about.faculty.members.faculty_michael.name": "Michael",
  "pages.about.faculty.members.faculty_michael.role": "Company Director and Management and Marketing Lead",
  "pages.about.faculty.overline": "Meet the team",
  "pages.about.faculty.title": "Our faculty",
  "pages.about.hero.image.alt": "County Hall Dance studio",
  "pages.about.hero.overline": "Our school",
  "pages.about.hero.subtitle": "Discover dance, movement and creative experiences at London's iconic County Hall",
  "pages.about.hero.title": "About County Hall Dance & Performing Arts School",
  "pages.about.meta.description": "Learn about County Hall Dance & Performing Arts School — our history, values, and faculty.",
  "pages.about.meta.title": "About Us",
  "pages.about.story.paragraphs.0": "County Hall Dance Centre is a new home for dance, movement and creativity in the heart of London. Located inside the iconic County Hall on the South Bank, the Centre brings together the best dance classes, workshops, social dances, private experiences and special events. More than a dance studio, it is a welcoming creative community where people can move, learn, connect and enjoy the arts together.",
  "pages.about.story.title": "Our story",
  "pages.about.values.items.0.description": "To make high-quality dance and mind-body classes open, welcoming, and connected in the heart of London.",
  "pages.about.values.items.0.title": "Mission",
  "pages.about.values.items.1.description": "To grow from a dedicated professional dance space into a creative destination that brings together dance, performing arts, music, visual arts, and international cultural exchange.",
  "pages.about.values.items.1.title": "Vision",
  "pages.about.values.items.2.description": "Move. Create. Connect. Belong. — helping adults of every background and level of experience build confidence, wellbeing, and a sense of belonging through the arts.",
  "pages.about.values.items.2.title": "Philosophy",
  "pages.about.values.items.3.description": "Robust policies ensuring every student feels secure and supported.",
  "pages.about.values.items.3.title": "Safeguarding",
  "pages.about.values.overline": "What guides us",
  "pages.about.values.title": "Our values",
  "pages.booking.form.description": "Tell us what you are looking for — studio hire, class booking, membership or a general question.",
  "pages.booking.form.fields.email_address.label": "Email address",
  "pages.booking.form.fields.email_address.placeholder": "you@example.com",
  "pages.booking.form.fields.enquiry_about.label": "Enquiry about",
  "pages.booking.form.fields.enquiry_about.options.classes_booking.label": "Classes Booking",
  "pages.booking.form.fields.enquiry_about.options.general_enquire.label": "General Enquire",
  "pages.booking.form.fields.enquiry_about.options.membership_booking.label": "Membership Booking",
  "pages.booking.form.fields.enquiry_about.options.studio_hire.label": "Studio Hire",
  "pages.booking.form.fields.full_name.label": "Full name",
  "pages.booking.form.fields.full_name.placeholder": "Your name",
  "pages.booking.form.fields.message.label": "Message",
  "pages.booking.form.fields.message.placeholder": "Please include any relevant details — dates, class names, group size, etc.",
  "pages.booking.form.fields.phone_optional.label": "Phone (optional)",
  "pages.booking.form.fields.phone_optional.placeholder": "+44 …",
  "pages.booking.form.selectplaceholder": "Select an option",
  "pages.booking.form.submitlabel": "Send message",
  "pages.booking.form.successmessage": "Thank you — your enquiry has been received. We will be in touch shortly.",
  "pages.booking.form.title": "Send an enquiry",
  "pages.booking.hero.overline": "We'd love to hear from you",
  "pages.booking.hero.subtitle": "Complete the form below and our team will respond by email within two working days.",
  "pages.booking.hero.title": "Booking & Enquiries",
  "pages.booking.meta.description": "Send a booking or general enquiry to County Hall Dance Centre — studio hire, classes, membership and more.",
  "pages.booking.meta.title": "Booking & Enquiries",
  "pages.classbooking.hero.overline": "Classes",
  "pages.classbooking.hero.subtitle": "View live availability and reserve your place through our booking partner.",
  "pages.classbooking.hero.title": "Booking",
  "pages.classbooking.intro": "Choose a class from the timetable and follow the booking link. Advance booking is recommended.",
  "pages.classbooking.meta.description": "Book adult dance and movement classes at County Hall Dance Centre.",
  "pages.classbooking.meta.title": "Class Booking",
  "pages.classbooking.sections.how_to_book.title": "How to book",
  "pages.classbooking.sections.policies.title": "Booking policies",
  "pages.classes.cta.label": "View timetable",
  "pages.classes.detaillabels.backlink": "Classes",
  "pages.classes.hero.overline": "Find your style",
  "pages.classes.hero.subtitle": "Adult dance and movement classes for every background and level — beginners welcome.",
  "pages.classes.hero.title": "Classes",
  "pages.classes.intro": "Explore adult classes in Contemporary, Chinese Dance, Tango, Yoga, Tai Chi and K-Pop. Every class is clearly labelled Beginner, Open Level or Intermediate.",
  "pages.classes.meta.description": "Adult classes in Contemporary, Chinese Dance, Tango, Yoga, Tai Chi and K-Pop at County Hall Dance Centre.",
  "pages.classes.meta.title": "Classes",
  "pages.classes.styles.chinese_dance.agegroups.adults.description": "Designed for adult learners at every stage.",
  "pages.classes.styles.chinese_dance.agegroups.adults.label": "Adults",
  "pages.classes.styles.chinese_dance.cta.label": "Book a class",
  "pages.classes.styles.chinese_dance.hero.image.alt": "Chinese dance class",
  "pages.classes.styles.chinese_dance.hero.overline": "Grace & line",
  "pages.classes.styles.chinese_dance.hero.subtitle": "Classical Chinese dance to build body control, flexibility and stage presence.",
  "pages.classes.styles.chinese_dance.hero.title": "Chinese Dance",
  "pages.classes.styles.chinese_dance.highlights.0.description": "Discover the artistry of classical Chinese movement.",
  "pages.classes.styles.chinese_dance.highlights.0.title": "Cultural expression",
  "pages.classes.styles.chinese_dance.highlights.1.description": "Develop line, poise and body awareness.",
  "pages.classes.styles.chinese_dance.highlights.1.title": "Flexibility & control",
  "pages.classes.styles.chinese_dance.highlights.2.description": "Beginners welcome — check the level on each class.",
  "pages.classes.styles.chinese_dance.highlights.2.title": "All levels",
  "pages.classes.styles.chinese_dance.intro.0": "Blending the grace, line and cultural expression of classical Chinese dance to build body control, flexibility and stage presence.",
  "pages.classes.styles.chinese_dance.metadescription": "Chinese dance classes blending classical grace, line and cultural expression for adults.",
  "pages.classes.styles.chinese_dance.name": "Chinese Dance",
  "pages.classes.styles.contemporary.agegroups.adults.description": "Open to all backgrounds — no dance experience needed.",
  "pages.classes.styles.contemporary.agegroups.adults.label": "Adults",
  "pages.classes.styles.contemporary.cta.label": "Book a class",
  "pages.classes.styles.contemporary.hero.image.alt": "Contemporary dance class",
  "pages.classes.styles.contemporary.hero.overline": "Modern dance",
  "pages.classes.styles.contemporary.hero.subtitle": "Develop coordination, strength and creativity through flow, space and physical expression.",
  "pages.classes.styles.contemporary.hero.title": "Contemporary",
  "pages.classes.styles.contemporary.highlights.0.description": "Explore space, dynamics and personal expression.",
  "pages.classes.styles.contemporary.highlights.0.title": "Creative movement",
  "pages.classes.styles.contemporary.highlights.1.description": "Build physical confidence through structured practice.",
  "pages.classes.styles.contemporary.highlights.1.title": "Strength & coordination",
  "pages.classes.styles.contemporary.highlights.2.description": "Classes labelled Beginner, Open Level or Intermediate.",
  "pages.classes.styles.contemporary.highlights.2.title": "All levels",
  "pages.classes.styles.contemporary.intro.0": "Develop coordination, strength and creativity through flow, space and physical expression.",
  "pages.classes.styles.contemporary.intro.1": "Ideal for adults keen to explore the language of modern dance.",
  "pages.classes.styles.contemporary.metadescription": "Contemporary dance classes for adults at County Hall Dance Centre — flow, space and physical expression.",
  "pages.classes.styles.contemporary.name": "Contemporary",
  "pages.classes.styles.k_pop.agegroups.adults_of_all_levels.description": "No previous dance experience needed.",
  "pages.classes.styles.k_pop.agegroups.adults_of_all_levels.label": "Adults of all levels",
  "pages.classes.styles.k_pop.cta.label": "Book a class",
  "pages.classes.styles.k_pop.hero.image.alt": "K-Pop dance class",
  "pages.classes.styles.k_pop.hero.overline": "Energy & style",
  "pages.classes.styles.k_pop.hero.subtitle": "High-energy choreography inspired by the world of K-Pop.",
  "pages.classes.styles.k_pop.hero.title": "K-Pop",
  "pages.classes.styles.k_pop.highlights.0.description": "Learn choreography step by step.",
  "pages.classes.styles.k_pop.highlights.0.title": "Full routines",
  "pages.classes.styles.k_pop.highlights.1.description": "Work on style, precision and expression.",
  "pages.classes.styles.k_pop.highlights.1.title": "Performance skills",
  "pages.classes.styles.k_pop.highlights.2.description": "A full-body workout that doesn't feel like one.",
  "pages.classes.styles.k_pop.highlights.2.title": "Fitness & fun",
  "pages.classes.styles.k_pop.intro.0": "Learn sharp, stylish routines inspired by the choreography of popular K-Pop songs. Classes break each routine into clear steps, building your coordination, stamina and performance confidence while you have a great time with a friendly group.",
  "pages.classes.styles.k_pop.metadescription": "K-Pop dance classes for adults at County Hall Dance Centre — learn high-energy routines inspired by today's biggest K-Pop hits.",
  "pages.classes.styles.k_pop.name": "K-Pop",
  "pages.classes.styles.tai_chi.agegroups.adults.description": "Suitable for every age and fitness level.",
  "pages.classes.styles.tai_chi.agegroups.adults.label": "Adults",
  "pages.classes.styles.tai_chi.cta.label": "Book a class",
  "pages.classes.styles.tai_chi.hero.image.alt": "Tai Chi class",
  "pages.classes.styles.tai_chi.hero.overline": "Flow & balance",
  "pages.classes.styles.tai_chi.hero.subtitle": "Cultivate balance, relaxation and body awareness through slow, flowing movement.",
  "pages.classes.styles.tai_chi.hero.title": "Tai Chi",
  "pages.classes.styles.tai_chi.highlights.0.description": "Slow, intentional movement for calm and focus.",
  "pages.classes.styles.tai_chi.highlights.0.title": "Mind-body practice",
  "pages.classes.styles.tai_chi.highlights.1.description": "Develop stability and gentle strength.",
  "pages.classes.styles.tai_chi.highlights.1.title": "Balance & awareness",
  "pages.classes.styles.tai_chi.highlights.2.description": "Welcoming to complete beginners.",
  "pages.classes.styles.tai_chi.highlights.2.title": "All levels",
  "pages.classes.styles.tai_chi.intro.0": "Cultivate balance, relaxation and body awareness through slow, flowing movement, breath and shifts of weight.",
  "pages.classes.styles.tai_chi.metadescription": "Tai Chi classes for adults — balance, relaxation and body awareness.",
  "pages.classes.styles.tai_chi.name": "Tai Chi",
  "pages.classes.styles.tango.agegroups.adults.description": "No partner or experience required to begin.",
  "pages.classes.styles.tango.agegroups.adults.label": "Adults",
  "pages.classes.styles.tango.cta.label": "Book a class",
  "pages.classes.styles.tango.hero.image.alt": "Tango class",
  "pages.classes.styles.tango.hero.overline": "Connection & musicality",
  "pages.classes.styles.tango.hero.subtitle": "Learn lead and follow, musicality and the etiquette of social dance.",
  "pages.classes.styles.tango.hero.title": "Tango",
  "pages.classes.styles.tango.highlights.0.description": "Lead, follow and floor etiquette from day one.",
  "pages.classes.styles.tango.highlights.0.title": "Social dance skills",
  "pages.classes.styles.tango.highlights.1.description": "Move with confidence to live and recorded tango music.",
  "pages.classes.styles.tango.highlights.1.title": "Musicality",
  "pages.classes.styles.tango.highlights.2.description": "Join our social dance nights and themed events.",
  "pages.classes.styles.tango.highlights.2.title": "Milongas & events",
  "pages.classes.styles.tango.intro.0": "Learn connection, lead and follow, musicality and the etiquette of social dance, building confidence from the very first steps.",
  "pages.classes.styles.tango.metadescription": "Tango classes for adults — connection, musicality and social dance etiquette.",
  "pages.classes.styles.tango.name": "Tango",
  "pages.classes.styles.yoga.agegroups.adults.description": "Open to beginners and returning practitioners.",
  "pages.classes.styles.yoga.agegroups.adults.label": "Adults",
  "pages.classes.styles.yoga.cta.label": "Book a class",
  "pages.classes.styles.yoga.hero.image.alt": "Yoga class",
  "pages.classes.styles.yoga.hero.overline": "Breath & stretch",
  "pages.classes.styles.yoga.hero.subtitle": "Improve flexibility and overall wellbeing through breath, stretch and focused practice.",
  "pages.classes.styles.yoga.hero.title": "Yoga",
  "pages.classes.styles.yoga.highlights.0.description": "Stretch, breathe and restore balance.",
  "pages.classes.styles.yoga.highlights.0.title": "Wellbeing focus",
  "pages.classes.styles.yoga.highlights.1.description": "A calm, focused environment for every body.",
  "pages.classes.styles.yoga.highlights.1.title": "Music-guided practice",
  "pages.classes.styles.yoga.highlights.2.description": "Check class information for level and format details.",
  "pages.classes.styles.yoga.highlights.2.title": "All levels",
  "pages.classes.styles.yoga.intro.0": "Improve flexibility and overall wellbeing through breath, stretch and focused, music-guided practice.",
  "pages.classes.styles.yoga.metadescription": "Yoga classes for adults — flexibility, breath and wellbeing at County Hall Dance Centre.",
  "pages.classes.styles.yoga.name": "Yoga",
  "pages.classesinfo.hero.overline": "Classes",
  "pages.classesinfo.hero.subtitle": "Explore our adult dance and movement programme and meet the teaching team.",
  "pages.classesinfo.hero.title": "Class Descriptions & Instructors",
  "pages.classesinfo.intro": "Every class is clearly labelled Beginner, Open Level or Intermediate. Beginners welcome — no dance experience needed.",
  "pages.classesinfo.meta.description": "Class descriptions and instructor profiles for adult classes at County Hall Dance Centre.",
  "pages.classesinfo.meta.title": "Class Descriptions & Instructors",
  "pages.classesinfo.sections.descriptions.title": "Class Descriptions",
  "pages.classesinfo.sections.instructors.title": "Instructors",
  "pages.common.eventdetailslink": "Details →",
  "pages.common.viewcourselink": "View course →",
  "pages.contact.details.address.0": "2nd Floor, County Hall Main Entrance",
  "pages.contact.details.address.1": "Belvedere Road",
  "pages.contact.details.address.2": "London SE1 7PB",
  "pages.contact.details.email": "info@countyhalldancecentre.com",
  "pages.contact.details.gettinghere": "Getting here: a five-minute walk from Waterloo and Westminster stations.",
  "pages.contact.details.hours": "Office hours: Mon – Fri, 9:00 – 17:30",
  "pages.contact.details.instagramlabel": "Instagram: @countyhalldancecentre",
  "pages.contact.details.membershiplabel": "Membership enquiries: membership@countyhalldancecentre.com",
  "pages.contact.details.phone": "+44 7728 617531",
  "pages.contact.details.title": "Studio details",
  "pages.contact.details.wechat": "WeChat: 18518614868",
  "pages.contact.form.description": "Complete the form below and we will respond within two working days.",
  "pages.contact.form.fields.email_address.label": "Email address",
  "pages.contact.form.fields.email_address.placeholder": "you@example.com",
  "pages.contact.form.fields.full_name.label": "Full name",
  "pages.contact.form.fields.full_name.placeholder": "Your name",
  "pages.contact.form.fields.message.label": "Message",
  "pages.contact.form.fields.message.placeholder": "How can we help?",
  "pages.contact.form.fields.phone_optional.label": "Phone (optional)",
  "pages.contact.form.fields.phone_optional.placeholder": "+44 …",
  "pages.contact.form.fields.subject.label": "Subject",
  "pages.contact.form.fields.subject.options.classes_timetable.label": "Classes & timetable",
  "pages.contact.form.fields.subject.options.events.label": "Events",
  "pages.contact.form.fields.subject.options.general_enquiry.label": "General enquiry",
  "pages.contact.form.fields.subject.options.gift_cards.label": "Gift cards",
  "pages.contact.form.fields.subject.options.membership.label": "Membership",
  "pages.contact.form.fields.subject.options.private_lessons_experiences.label": "Private lessons & experiences",
  "pages.contact.form.fields.subject.options.studio_hire.label": "Studio hire",
  "pages.contact.form.selectplaceholder": "Select an option",
  "pages.contact.form.submitlabel": "Send message",
  "pages.contact.form.successmessage": "Thank you — your message has been received. We will be in touch shortly.",
  "pages.contact.form.title": "Send an enquiry",
  "pages.contact.hero.overline": "We'd love to hear from you",
  "pages.contact.hero.subtitle": "Questions about classes, courses, private events, or anything else — send us a message.",
  "pages.contact.hero.title": "Contact",
  "pages.contact.map.directionslabel": "Open in Google Maps →",
  "pages.contact.map.title": "Find us",
  "pages.contact.meta.description": "Get in touch with County Hall Dance & Performing Arts School.",
  "pages.contact.meta.title": "Contact",
  "pages.courses.detaillabels.backlink": "All courses",
  "pages.courses.detaillabels.duration": "Duration",
  "pages.courses.detaillabels.price": "Price",
  "pages.courses.detaillabels.schedule": "Schedule",
  "pages.courses.hero.overline": "Structured progression",
  "pages.courses.hero.subtitle": "Immersive term programmes designed to deepen technique, artistry, and performance readiness.",
  "pages.courses.hero.title": "Courses",
  "pages.courses.intro": "Courses differ from drop-in classes — they follow a curated syllabus across a full term, culminating in an informal sharing or assessment where appropriate.",
  "pages.courses.items.adult_ballet_open.cta.label": "Enrol via timetable",
  "pages.courses.items.adult_ballet_open.description.0": "Rebuild strength and grace at the barre and in centre, with modifications offered throughout.",
  "pages.courses.items.adult_ballet_open.description.1": "Each block introduces new enchaînements while revisiting core principles.",
  "pages.courses.items.adult_ballet_open.duration": "6-week blocks",
  "pages.courses.items.adult_ballet_open.excerpt": "A welcoming ballet class for adults — beginners and returners alike.",
  "pages.courses.items.adult_ballet_open.image.alt": "Adult ballet open course",
  "pages.courses.items.adult_ballet_open.includes.0": "Weekly 75-minute class",
  "pages.courses.items.adult_ballet_open.includes.1": "Technique notes via email",
  "pages.courses.items.adult_ballet_open.includes.2": "Optional end-of-block class video",
  "pages.courses.items.adult_ballet_open.level": "All levels",
  "pages.courses.items.adult_ballet_open.metadescription": "Open-level adult ballet course at CHD PAS, London.",
  "pages.courses.items.adult_ballet_open.price": "£96 per block",
  "pages.courses.items.adult_ballet_open.schedule": "Mondays, 19:00 – 20:15",
  "pages.courses.items.adult_ballet_open.term": "Rolling enrolment",
  "pages.courses.items.adult_ballet_open.title": "Adult Ballet Open",
  "pages.courses.items.junior_ballet_foundation.cta.label": "Enrol via timetable",
  "pages.courses.items.junior_ballet_foundation.description.0": "This course introduces young dancers to the fundamentals of ballet posture, port de bras, and basic allegro.",
  "pages.courses.items.junior_ballet_foundation.description.1": "Classes are taught in a nurturing environment with clear expectations and plenty of encouragement.",
  "pages.courses.items.junior_ballet_foundation.duration": "12 weeks",
  "pages.courses.items.junior_ballet_foundation.excerpt": "A twelve-week introduction to classical ballet for ages 6–9.",
  "pages.courses.items.junior_ballet_foundation.image.alt": "Junior ballet foundation course",
  "pages.courses.items.junior_ballet_foundation.includes.0": "Weekly 60-minute class",
  "pages.courses.items.junior_ballet_foundation.includes.1": "Course handbook and practice notes",
  "pages.courses.items.junior_ballet_foundation.includes.2": "End-of-term studio sharing",
  "pages.courses.items.junior_ballet_foundation.level": "Beginner – Elementary",
  "pages.courses.items.junior_ballet_foundation.metadescription": "Twelve-week junior ballet foundation course for ages 6–9 at CHD PAS.",
  "pages.courses.items.junior_ballet_foundation.price": "£168 per term",
  "pages.courses.items.junior_ballet_foundation.schedule": "Saturdays, 10:00 – 11:00",
  "pages.courses.items.junior_ballet_foundation.term": "Autumn Term 2026",
  "pages.courses.items.junior_ballet_foundation.title": "Junior Ballet Foundation",
  "pages.courses.items.musical_theatre_performance.cta.label": "Enrol via timetable",
  "pages.courses.items.musical_theatre_performance.description.0": "Sing, dance, and act your way through a selected musical number, rehearsed for a small invited audience.",
  "pages.courses.items.musical_theatre_performance.description.1": "Vocal coaching and ensemble work are integrated throughout the term.",
  "pages.courses.items.musical_theatre_performance.duration": "14 weeks",
  "pages.courses.items.musical_theatre_performance.excerpt": "Triple-threat training culminating in a staged musical excerpt.",
  "pages.courses.items.musical_theatre_performance.image.alt": "Musical theatre performance course",
  "pages.courses.items.musical_theatre_performance.includes.0": "Weekly 3-hour session",
  "pages.courses.items.musical_theatre_performance.includes.1": "Vocal warm-up resources",
  "pages.courses.items.musical_theatre_performance.includes.2": "Costume hire for final sharing",
  "pages.courses.items.musical_theatre_performance.level": "Intermediate – Advanced",
  "pages.courses.items.musical_theatre_performance.metadescription": "Musical theatre performance course for intermediate and advanced students.",
  "pages.courses.items.musical_theatre_performance.price": "£320 per term",
  "pages.courses.items.musical_theatre_performance.schedule": "Saturdays, 13:00 – 16:00",
  "pages.courses.items.musical_theatre_performance.term": "Spring Term 2027",
  "pages.courses.items.musical_theatre_performance.title": "Musical Theatre Performance",
  "pages.courses.items.teen_contemporary_intensive.cta.label": "Enrol via timetable",
  "pages.courses.items.teen_contemporary_intensive.description.0": "Students explore release technique, contact principles, and choreographic tasks across a focused ten-week block.",
  "pages.courses.items.teen_contemporary_intensive.description.1": "The course prepares dancers for school showcases and optional audition pieces.",
  "pages.courses.items.teen_contemporary_intensive.duration": "10 weeks",
  "pages.courses.items.teen_contemporary_intensive.excerpt": "Develop contemporary technique, improvisation, and performance skills.",
  "pages.courses.items.teen_contemporary_intensive.image.alt": "Teen contemporary intensive course",
  "pages.courses.items.teen_contemporary_intensive.includes.0": "Weekly 90-minute class",
  "pages.courses.items.teen_contemporary_intensive.includes.1": "Guest artist Q&A session",
  "pages.courses.items.teen_contemporary_intensive.includes.2": "Performance workshop",
  "pages.courses.items.teen_contemporary_intensive.level": "Intermediate",
  "pages.courses.items.teen_contemporary_intensive.metadescription": "Intermediate contemporary course for teens at County Hall Dance.",
  "pages.courses.items.teen_contemporary_intensive.price": "£195 per term",
  "pages.courses.items.teen_contemporary_intensive.schedule": "Wednesdays, 17:30 – 19:00",
  "pages.courses.items.teen_contemporary_intensive.term": "Autumn Term 2026",
  "pages.courses.items.teen_contemporary_intensive.title": "Teen Contemporary Intensive",
  "pages.courses.meta.description": "Term-length dance and performing arts courses with structured progression at CHD PAS.",
  "pages.courses.meta.title": "Courses",
  "pages.events.categories.cross_arts_events.hero.overline": "Events",
  "pages.events.categories.cross_arts_events.hero.subtitle": "Where dance meets music, visual art and international cultural exchange.",
  "pages.events.categories.cross_arts_events.hero.title": "Cross-Arts Events",
  "pages.events.categories.cross_arts_events.intro": "Our Dance Meets Arts programme brings together movement, live music, visual art and cultural celebration.",
  "pages.events.categories.cross_arts_events.meta.description": "Dance Meets Arts cross-disciplinary events at County Hall Dance Centre.",
  "pages.events.categories.cross_arts_events.meta.title": "Cross-Arts Events",
  "pages.events.categories.cross_arts_events.sections.programme.title": "Programme",
  "pages.events.categories.cross_arts_events.sections.upcoming.title": "Upcoming events",
  "pages.events.categories.masterclasses.hero.overline": "Events",
  "pages.events.categories.masterclasses.hero.subtitle": "Learn from visiting artists and specialists in intimate studio settings.",
  "pages.events.categories.masterclasses.hero.title": "Masterclasses",
  "pages.events.categories.masterclasses.intro": "Masterclasses bring professional artists to County Hall for intensive teaching sessions across styles and levels.",
  "pages.events.categories.masterclasses.meta.description": "Guest artist masterclasses at County Hall Dance Centre.",
  "pages.events.categories.masterclasses.meta.title": "Masterclasses",
  "pages.events.categories.masterclasses.sections.levels.title": "Levels & requirements",
  "pages.events.categories.masterclasses.sections.upcoming.title": "Upcoming masterclasses",
  "pages.events.categories.milonga.hero.overline": "Events",
  "pages.events.categories.milonga.hero.subtitle": "Social tango evenings with live and recorded music in our South Bank studio.",
  "pages.events.categories.milonga.hero.title": "Milonga",
  "pages.events.categories.milonga.intro": "Join us for regular milongas — welcoming social dance nights for tango dancers of every level.",
  "pages.events.categories.milonga.meta.description": "Tango milonga social dance events at County Hall Dance Centre.",
  "pages.events.categories.milonga.meta.title": "Milonga",
  "pages.events.categories.milonga.sections.upcoming.title": "Upcoming milongas",
  "pages.events.categories.milonga.sections.what_to_expect.title": "What to expect",
  "pages.events.categories.performances.hero.overline": "Events",
  "pages.events.categories.performances.hero.subtitle": "Ticketed showcases, sharings and performance events throughout the year.",
  "pages.events.categories.performances.hero.title": "Performances",
  "pages.events.categories.performances.intro": "Celebrate the work of our community in performances ranging from informal sharings to ticketed showcase evenings.",
  "pages.events.categories.performances.meta.description": "Performances and showcases at County Hall Dance Centre.",
  "pages.events.categories.performances.meta.title": "Performances",
  "pages.events.categories.performances.sections.tickets.title": "Tickets",
  "pages.events.categories.performances.sections.upcoming.title": "Upcoming performances",
  "pages.events.categories.social_dance_nights.hero.overline": "Events",
  "pages.events.categories.social_dance_nights.hero.subtitle": "Themed evenings celebrating dance styles, music and community.",
  "pages.events.categories.social_dance_nights.hero.title": "Social Dance Nights",
  "pages.events.categories.social_dance_nights.intro": "From salsa socials to cross-style celebrations, our social nights are open to adults who love to move and connect.",
  "pages.events.categories.social_dance_nights.meta.description": "Themed social dance evenings at County Hall Dance Centre.",
  "pages.events.categories.social_dance_nights.meta.title": "Social Dance Nights",
  "pages.events.categories.social_dance_nights.sections.how_to_join.title": "How to join",
  "pages.events.categories.social_dance_nights.sections.upcoming.title": "Upcoming social nights",
  "pages.events.categories.workshops.hero.overline": "Events",
  "pages.events.categories.workshops.hero.subtitle": "One-off intensives and taster sessions with guest artists and faculty.",
  "pages.events.categories.workshops.hero.title": "Workshops",
  "pages.events.categories.workshops.intro": "Workshops offer a focused opportunity to explore a style, technique or theme in a single session or short series.",
  "pages.events.categories.workshops.meta.description": "Dance and movement workshops at County Hall Dance Centre.",
  "pages.events.categories.workshops.meta.title": "Workshops",
  "pages.events.categories.workshops.sections.booking.title": "Booking",
  "pages.events.categories.workshops.sections.upcoming.title": "Upcoming workshops",
  "pages.events.categorylabels.backlink": "← All events",
  "pages.events.detaillabels.backlink": "← All events",
  "pages.events.detaillabels.date": "Date",
  "pages.events.detaillabels.location": "Location",
  "pages.events.hero.overline": "What's on",
  "pages.events.hero.subtitle": "One-off workshops, guest artist intensives, and ticketed performances throughout the year.",
  "pages.events.hero.title": "Events & Masterclasses",
  "pages.events.intro": "Book directly via the links below. Event payments are processed securely through Stripe — class bookings remain on our timetable system.",
  "pages.events.items.contemporary_intensive_maya_chen.booknow.label": "Book Now",
  "pages.events.items.contemporary_intensive_maya_chen.date": "Saturday 18 October 2026",
  "pages.events.items.contemporary_intensive_maya_chen.description.0": "Join internationally recognised choreographer Maya Chen for a day of contemporary training at intermediate level and above.",
  "pages.events.items.contemporary_intensive_maya_chen.description.1": "The morning focuses on floor work and release principles; the afternoon introduces excerpts from Maya's touring repertory.",
  "pages.events.items.contemporary_intensive_maya_chen.description.2": "Please bring knee pads and water. Places are limited to 24 participants.",
  "pages.events.items.contemporary_intensive_maya_chen.excerpt": "A full-day intensive exploring release technique and repertory with guest artist Maya Chen.",
  "pages.events.items.contemporary_intensive_maya_chen.image.alt": "Contemporary dance intensive workshop",
  "pages.events.items.contemporary_intensive_maya_chen.location": "Studio A",
  "pages.events.items.contemporary_intensive_maya_chen.title": "Contemporary Intensive with Maya Chen",
  "pages.events.items.junior_ballet_masterclass.booknow.label": "Book Now",
  "pages.events.items.junior_ballet_masterclass.date": "Sunday 26 October 2026",
  "pages.events.items.junior_ballet_masterclass.description.0": "Led by a guest RAD examiner, this masterclass refines alignment, épaulement, and petite allegro.",
  "pages.events.items.junior_ballet_masterclass.description.1": "Suitable for students currently studying Grade 2–4 or equivalent.",
  "pages.events.items.junior_ballet_masterclass.excerpt": "A special masterclass for junior ballet students aged 8–12.",
  "pages.events.items.junior_ballet_masterclass.image.alt": "Junior ballet masterclass in progress",
  "pages.events.items.junior_ballet_masterclass.location": "Studio B",
  "pages.events.items.junior_ballet_masterclass.title": "Junior Ballet Masterclass",
  "pages.events.items.musical_theatre_workshop_day.booknow.label": "Book Now",
  "pages.events.items.musical_theatre_workshop_day.date": "Saturday 8 November 2026",
  "pages.events.items.musical_theatre_workshop_day.description.0": "A lively day of triple-threat training, ending with a short sharing for friends and family.",
  "pages.events.items.musical_theatre_workshop_day.description.1": "Open to ages 10–16 with some prior dance or drama experience recommended.",
  "pages.events.items.musical_theatre_workshop_day.excerpt": "Sing, dance, and act through a full musical theatre workshop day.",
  "pages.events.items.musical_theatre_workshop_day.image.alt": "Musical theatre workshop participants on stage",
  "pages.events.items.musical_theatre_workshop_day.location": "Main Hall",
  "pages.events.items.musical_theatre_workshop_day.title": "Musical Theatre Workshop Day",
  "pages.events.items.winter_showcase.booknow.label": "Book Now",
  "pages.events.items.winter_showcase.date": "Friday 12 December 2026",
  "pages.events.items.winter_showcase.description.0": "Celebrate the talent of the CHD PAS community in an evening of ballet, contemporary, jazz, and musical theatre.",
  "pages.events.items.winter_showcase.description.1": "Doors open at 18:30; performance begins at 19:00. Running time approximately 90 minutes including interval.",
  "pages.events.items.winter_showcase.excerpt": "Our annual winter showcase featuring students from every discipline.",
  "pages.events.items.winter_showcase.image.alt": "Winter showcase performance lighting",
  "pages.events.items.winter_showcase.location": "County Hall Theatre",
  "pages.events.items.winter_showcase.title": "Winter Showcase — Tickets On Sale",
  "pages.events.meta.description": "Masterclasses, workshops, and performances at County Hall Dance & Performing Arts School.",
  "pages.events.meta.title": "Events & Masterclasses",
  "pages.faq.cta.button.label": "Contact us",
  "pages.faq.cta.text": "Can't find what you need?",
  "pages.faq.hero.overline": "Help centre",
  "pages.faq.hero.subtitle": "Quick answers to common questions. Still unsure? Contact our friendly team.",
  "pages.faq.hero.title": "Frequently asked questions",
  "pages.faq.items.faq_1.answer": "Visit our Timetable & Booking page and use the booking widget to select a class. You will be directed to our external booking partner to complete registration and payment.",
  "pages.faq.items.faq_1.question": "How do I book a class?",
  "pages.faq.items.faq_2.answer": "Yes — you can book a trial class from our Timetable page. Please note that trial classes are not free. If you're unsure which class suits you, contact us and we'll help you choose.",
  "pages.faq.items.faq_2.question": "Can I try a class before committing?",
  "pages.faq.items.faq_4.answer": "Courses run for a fixed term with a structured syllabus and limited places. Regular classes can often be booked on a rolling basis via the timetable.",
  "pages.faq.items.faq_4.question": "How are courses different from regular classes?",
  "pages.faq.items.faq_6.answer": "Events are booked directly via the Book Now button on each event page. Payments are processed securely through Stripe.",
  "pages.faq.items.faq_6.question": "How do I book an event or masterclass?",
  "pages.faq.items.faq_7.answer": "We're a five-minute walk from both Waterloo and Westminster stations.",
  "pages.faq.items.faq_7.question": "How do I get there?",
  "pages.faq.items.faq_hire.answer": "Yes — our 70 m² vinyl-floor studio and 200 m² wooden-floor hall can be hired separately or together, from £200 per hour (member rates available). See Studio Hire for details.",
  "pages.faq.items.faq_hire.question": "Can I hire the studio?",
  "pages.faq.meta.description": "Frequently asked questions about classes, courses, and bookings at CHD PAS.",
  "pages.faq.meta.title": "FAQ",
  "pages.giftcards.hero.overline": "A thoughtful gift",
  "pages.giftcards.hero.subtitle": "Perfect for birthdays, holidays, or encouraging someone to take their first class.",
  "pages.giftcards.hero.title": "Gift Cards",
  "pages.giftcards.intro": "Gift cards can be redeemed against classes, courses, workshops, and merchandise. They are delivered by email and valid for twelve months from purchase.",
  "pages.giftcards.meta.description": "Give the gift of dance with a CHD PAS gift card.",
  "pages.giftcards.meta.title": "Gift Cards",
  "pages.giftcards.options.gift_100.amount": "£100",
  "pages.giftcards.options.gift_100.cta.label": "Buy £100 card",
  "pages.giftcards.options.gift_100.description": "A generous gift towards a full course or multiple masterclasses.",
  "pages.giftcards.options.gift_100.title": "£100 Gift Card",
  "pages.giftcards.options.gift_25.amount": "£25",
  "pages.giftcards.options.gift_25.cta.label": "Buy £25 card",
  "pages.giftcards.options.gift_25.description": "Ideal for a single workshop or as a contribution towards term fees.",
  "pages.giftcards.options.gift_25.title": "£25 Gift Card",
  "pages.giftcards.options.gift_50.amount": "£50",
  "pages.giftcards.options.gift_50.cta.label": "Buy £50 card",
  "pages.giftcards.options.gift_50.description": "Covers several drop-in classes or part of a term enrolment.",
  "pages.giftcards.options.gift_50.title": "£50 Gift Card",
  "pages.giftcards.terms": "Gift cards are non-refundable and cannot be exchanged for cash. Remaining balances stay on the card until used. Contact us for custom amounts.",
  "pages.joinus.hero.overline": "About Us",
  "pages.joinus.hero.subtitle": "Teaching, creative and operational opportunities at County Hall Dance Centre.",
  "pages.joinus.hero.title": "Join Us",
  "pages.joinus.intro": "We are building a welcoming creative community on the South Bank. Expressions of interest from teachers, artists and collaborators are welcome.",
  "pages.joinus.meta.description": "Join the team at County Hall Dance Centre.",
  "pages.joinus.meta.title": "Join Us",
  "pages.joinus.sections.apply.title": "How to apply",
  "pages.joinus.sections.opportunities.title": "Opportunities",
  "pages.membership.overview.benefits.items.0.body": "Save on workshops, masterclasses and intensive courses.",
  "pages.membership.overview.benefits.items.0.title": "Workshop & masterclass discounts",
  "pages.membership.overview.benefits.items.1.body": "Be first to sign up for performances, showcases and special events.",
  "pages.membership.overview.benefits.items.1.title": "Priority registration",
  "pages.membership.overview.benefits.items.2.body": "Reduced prices on performance and event tickets.",
  "pages.membership.overview.benefits.items.2.title": "Event ticket discounts",
  "pages.membership.overview.benefits.items.3.body": "Savings on County Hall merchandise, dancewear and dance shoes.",
  "pages.membership.overview.benefits.items.3.title": "Merchandise discounts",
  "pages.membership.overview.benefits.items.4.body": "Member rates on studio and practice-space hire (from £100 per hour on weekdays).",
  "pages.membership.overview.benefits.items.4.title": "Reduced studio hire",
  "pages.membership.overview.benefits.items.5.body": "Exclusive discounts with our partner businesses.",
  "pages.membership.overview.benefits.items.5.title": "Partner offers",
  "pages.membership.overview.benefits.items.6.body": "Community classes, parties, theatre trips and social gatherings.",
  "pages.membership.overview.benefits.items.6.title": "Members-only events",
  "pages.membership.overview.benefits.items.7.body": "Join our private members' group to stay connected.",
  "pages.membership.overview.benefits.items.7.title": "Member community",
  "pages.membership.overview.benefits.items.8.body": "Earn rewards when a friend joins.",
  "pages.membership.overview.benefits.items.8.title": "Refer a friend",
  "pages.membership.overview.benefits.items.9.body": "Collect points for attendance and redeem them for rewards.",
  "pages.membership.overview.benefits.items.9.title": "Points & rewards",
  "pages.membership.overview.benefits.title": "Member benefits",
  "pages.membership.overview.cta.body": "Email our membership team and we'll help you find the plan that suits you best.",
  "pages.membership.overview.cta.button.label": "Join now",
  "pages.membership.overview.cta.secondary": "membership@countyhalldancecentre.com",
  "pages.membership.overview.cta.title": "Ready to join?",
  "pages.membership.overview.faq.items.membership_faq_hire.answer": "Simply mention your membership when you enquire.",
  "pages.membership.overview.faq.items.membership_faq_hire.question": "How do I get member rates for studio hire?",
  "pages.membership.overview.faq.items.membership_faq_styles.answer": "Membership covers our class styles: Contemporary, Chinese Dance, Tango, Yoga, Tai Chi and K-Pop.",
  "pages.membership.overview.faq.items.membership_faq_styles.question": "Which classes are included?",
  "pages.membership.overview.faq.items.membership_faq_trial.answer": "We don't offer free trial classes, but you're welcome to book a trial class before you join. Email membership@countyhalldancecentre.com and we'll gladly help you choose the class and plan that's right for you.",
  "pages.membership.overview.faq.items.membership_faq_trial.question": "Do you offer free trial classes?",
  "pages.membership.overview.faq.title": "Membership FAQ",
  "pages.membership.overview.hero.overline": "Dance more, belong more",
  "pages.membership.overview.hero.subtitle": "Make dance part of your week — and become part of a creative community at London's iconic County Hall.",
  "pages.membership.overview.hero.title": "Membership",
  "pages.membership.overview.howtojoin.steps.0": "Choose your plan.",
  "pages.membership.overview.howtojoin.steps.1": "Email us at membership@countyhalldancecentre.com with the plan you'd like.",
  "pages.membership.overview.howtojoin.steps.2": "Complete your registration and payment.",
  "pages.membership.overview.howtojoin.steps.3": "Start booking classes and enjoying your member benefits.",
  "pages.membership.overview.howtojoin.title": "How to join",
  "pages.membership.overview.intro": "Membership is the best way to experience County Hall Dance Centre. Choose a plan that suits your routine and enjoy classes across Contemporary, Chinese Dance, Tango, Yoga, Tai Chi and K-Pop — plus exclusive discounts, priority access to events and a friendly community of fellow movers. Whether you're starting out or deepening your practice, our members get more from every visit.",
  "pages.membership.overview.meta.description": "County Hall Dance Centre membership — monthly, quarterly and annual plans with member discounts, priority booking, community events and reduced studio hire rates.",
  "pages.membership.overview.meta.title": "Membership",
  "pages.membership.overview.plans.cta.label": "Join now",
  "pages.membership.overview.plans.items.annual.body": "Our best value. A full year of dance, community and member-only perks.",
  "pages.membership.overview.plans.items.annual.price": "£[TBC] / year",
  "pages.membership.overview.plans.items.annual.title": "Annual Membership",
  "pages.membership.overview.plans.items.monthly.body": "Flexible and easy to start. Ideal if you want to build a regular practice without a long commitment.",
  "pages.membership.overview.plans.items.monthly.price": "£[TBC] / month",
  "pages.membership.overview.plans.items.monthly.title": "Monthly Membership",
  "pages.membership.overview.plans.items.quarterly.body": "Three months of classes and member benefits — a great way to see real progress.",
  "pages.membership.overview.plans.items.quarterly.price": "£[TBC] / quarter",
  "pages.membership.overview.plans.items.quarterly.title": "Quarterly Membership",
  "pages.membership.overview.plans.title": "Plans",
  "pages.membership.overview.styles.items.0": "Contemporary",
  "pages.membership.overview.styles.items.1": "Chinese Dance",
  "pages.membership.overview.styles.items.2": "Tango",
  "pages.membership.overview.styles.items.3": "Yoga",
  "pages.membership.overview.styles.items.4": "Tai Chi",
  "pages.membership.overview.styles.items.5": "K-Pop",
  "pages.membership.overview.styles.title": "Class styles included",
  "pages.membership.subpages.booking_access.hero.overline": "Membership",
  "pages.membership.subpages.booking_access.hero.subtitle": "How members reserve classes and events through our booking system.",
  "pages.membership.subpages.booking_access.hero.title": "Booking Access",
  "pages.membership.subpages.booking_access.intro": "Members will receive booking access through our online timetable and companion app — details to follow via our app partner.",
  "pages.membership.subpages.booking_access.meta.description": "Member booking access at County Hall Dance Centre.",
  "pages.membership.subpages.booking_access.meta.title": "Booking Access",
  "pages.membership.subpages.booking_access.sections.member_booking.title": "Member booking",
  "pages.membership.subpages.booking_access.sections.support.title": "Support",
  "pages.membership.subpages.member_benefits.hero.overline": "Membership",
  "pages.membership.subpages.member_benefits.hero.subtitle": "A more flexible way to keep dancing, join events and belong to the community.",
  "pages.membership.subpages.member_benefits.hero.title": "Member Benefits",
  "pages.membership.subpages.member_benefits.intro": "Membership offers ongoing access to classes, events and community benefits — details to be confirmed before launch.",
  "pages.membership.subpages.member_benefits.meta.description": "Benefits of membership at County Hall Dance Centre.",
  "pages.membership.subpages.member_benefits.meta.title": "Member Benefits",
  "pages.membership.subpages.member_benefits.sections.benefits.title": "What's included",
  "pages.membership.subpages.member_benefits.sections.how_to_join.title": "How to join",
  "pages.membership.subpages.monthly_passes.hero.overline": "Membership",
  "pages.membership.subpages.monthly_passes.hero.subtitle": "Flexible monthly options for regular class attendance.",
  "pages.membership.subpages.monthly_passes.hero.title": "Monthly Passes",
  "pages.membership.subpages.monthly_passes.intro": "Monthly passes will be published with validity, cancellation policy and transferability before online booking opens.",
  "pages.membership.subpages.monthly_passes.meta.description": "Monthly pass options at County Hall Dance Centre.",
  "pages.membership.subpages.monthly_passes.meta.title": "Monthly Passes",
  "pages.membership.subpages.monthly_passes.sections.pass_options.title": "Pass options",
  "pages.membership.subpages.monthly_passes.sections.terms.title": "Terms",
  "pages.membershipterms.hero.overline": "About Us",
  "pages.membershipterms.hero.subtitle": "Terms governing membership passes, booking access and cancellation.",
  "pages.membershipterms.hero.title": "Membership Terms",
  "pages.membershipterms.intro": "Final membership terms, including validity, cancellation policy and transferability, will be published before online booking opens.",
  "pages.membershipterms.meta.description": "Membership terms and conditions at County Hall Dance Centre.",
  "pages.membershipterms.meta.title": "Membership Terms",
  "pages.membershipterms.sections.cancellation.title": "Cancellation policy",
  "pages.membershipterms.sections.general.title": "General terms",
  "pages.privatelessons.cta.body": "Send us a few details and our team will be in touch.",
  "pages.privatelessons.cta.button.label": "Enquire now",
  "pages.privatelessons.cta.secondary": "WeChat: 18518614868 · Instagram: @countyhalldancecentre",
  "pages.privatelessons.cta.title": "Plan your experience",
  "pages.privatelessons.hero.overline": "Tailored for you",
  "pages.privatelessons.hero.subtitle": "Personal coaching and bespoke dance experiences for individuals, couples, groups and organisations — in a beautiful studio at County Hall.",
  "pages.privatelessons.hero.title": "Private Lessons & Experiences",
  "pages.privatelessons.howitworks.steps.0.body": "the occasion, group size and preferred dates.",
  "pages.privatelessons.howitworks.steps.0.title": "Tell us your plans",
  "pages.privatelessons.howitworks.steps.1.body": "style, teacher, length and a clear quote.",
  "pages.privatelessons.howitworks.steps.1.title": "We design your session",
  "pages.privatelessons.howitworks.steps.2.body": "arrive, relax and dance.",
  "pages.privatelessons.howitworks.steps.2.title": "Enjoy the experience",
  "pages.privatelessons.howitworks.title": "How it works",
  "pages.privatelessons.intro": "Whether you want focused one-to-one coaching, a first dance to remember or a celebration your guests will talk about for years, we'll design a session around your goals, your group and your schedule. Every experience is led by experienced teachers and artists, and takes place in our studios on the South Bank.",
  "pages.privatelessons.meta.description": "Private dance lessons and bespoke experiences at County Hall — one-to-one coaching, couples' dance, wedding first dances, group experiences, corporate events and workshops.",
  "pages.privatelessons.meta.title": "Private Lessons & Experiences",
  "pages.privatelessons.sections.corporate.body": "Bring your team together through movement. Our corporate sessions are an energising, inclusive alternative to the usual away day — no dance experience required. We design each event around your goals, whether that's building trust and communication, sparking creativity, welcoming new starters or simply giving your people a well-earned reward. Choose a short, high-energy session to open a conference, a half-day team-building workshop, or a full event combining movement with meetings in our fully equipped spaces, complete with sound system, microphones, tables and chairs. Sessions can be tailored to group size and schedule, and our team will handle the planning so you can focus on your people.",
  "pages.privatelessons.sections.corporate.cta.label": "Enquire",
  "pages.privatelessons.sections.corporate.gallery.0.alt": "Corporate group movement session",
  "pages.privatelessons.sections.corporate.gallery.1.alt": "Team workshop in the dance studio",
  "pages.privatelessons.sections.corporate.gallery.2.alt": "Professional studio environment",
  "pages.privatelessons.sections.corporate.title": "Corporate Events",
  "pages.privatelessons.sections.couples.body": "Dancing together is one of the most joyful ways to connect. Our couples' sessions offer a relaxed, private setting where you can learn side by side — no experience needed. Celebrate an anniversary or special occasion with a memorable shared experience, surprise your partner with something new, or take your first steps into social dance and learn the essentials of leading, following and moving to music together. Your teacher will tailor the style and pace to you, whether you'd like a light-hearted one-off session or a series of lessons that builds real confidence on the dance floor. Many couples find it becomes a favourite ritual of their week.",
  "pages.privatelessons.sections.couples.cta.label": "Enquire",
  "pages.privatelessons.sections.couples.gallery.0.alt": "Couple learning partner dance",
  "pages.privatelessons.sections.couples.gallery.1.alt": "Couples dance experience at County Hall",
  "pages.privatelessons.sections.couples.gallery.2.alt": "Pair practising movement in the studio",
  "pages.privatelessons.sections.couples.title": "Couples' Dance",
  "pages.privatelessons.sections.groups.body": "Celebrate with the people who matter most. Our group experiences are perfect for hen and stag parties, birthdays, reunions and friendship groups, and can welcome up to 120 guests. Choose from themed sessions across our styles — a tango taster, a K-Pop routine, a Chinese dance experience or a creative movement workshop — and our teachers will lead a fun, inclusive session that everyone can enjoy, whatever their experience. You're welcome to bring your own music and drinks to make the occasion truly yours, and we can help you plan timings, the space and the flow of the day so you can relax and enjoy the celebration with your guests.",
  "pages.privatelessons.sections.groups.cta.label": "Enquire",
  "pages.privatelessons.sections.groups.gallery.0.alt": "Group dance experience",
  "pages.privatelessons.sections.groups.gallery.1.alt": "Musical theatre themed workshop",
  "pages.privatelessons.sections.groups.gallery.2.alt": "Group class in the studio",
  "pages.privatelessons.sections.groups.title": "Group Experiences",
  "pages.privatelessons.sections.one_to_one.body": "Our one-to-one lessons are built entirely around you. Every journey begins with a goal assessment, where your teacher gets to know your experience, strengths and ambitions, then designs a personalised training plan to match. Sessions can focus on technique — strength, flexibility, control and precision — or on performance quality, musicality and stage presence. We also offer targeted preparation for dance exams and auditions, helping you refine your repertoire, build confidence and walk into the room ready. Whether you're an absolute beginner who prefers to learn privately or an experienced dancer refining the details, you'll progress faster with undivided attention and honest, supportive feedback.",
  "pages.privatelessons.sections.one_to_one.cta.label": "Enquire",
  "pages.privatelessons.sections.one_to_one.gallery.0.alt": "One-to-one private dance lesson",
  "pages.privatelessons.sections.one_to_one.gallery.1.alt": "Dancer in a private contemporary session",
  "pages.privatelessons.sections.one_to_one.gallery.2.alt": "Instructor working with an individual student",
  "pages.privatelessons.sections.one_to_one.title": "One-to-One Lessons",
  "pages.privatelessons.sections.schools.body": "We offer tailored dance and movement workshops for universities, colleges, community groups and cultural organisations. Led by experienced teachers and artists, workshops can introduce a new style, explore the cultural roots of forms such as classical Chinese dance and Tai Chi, or support creative, wellbeing and performance programmes. Every session is planned around your group's size, level and learning goals, and can be delivered as a one-off experience or a series. Tell us about your group and what you hope to achieve, and we'll put together a programme and quote that fits.",
  "pages.privatelessons.sections.schools.cta.label": "Enquire",
  "pages.privatelessons.sections.schools.gallery.0.alt": "Young dancers in a workshop",
  "pages.privatelessons.sections.schools.gallery.1.alt": "Workshop session with students",
  "pages.privatelessons.sections.schools.gallery.2.alt": "Ballet foundation class",
  "pages.privatelessons.sections.schools.title": "Workshops for Organisations",
  "pages.privatelessons.sections.wedding.body": "Your first dance should feel like you — and we'll help you make it unforgettable. We start by helping you choose or edit your song, then create choreography that suits your music, your style and your comfort level, from a simple, elegant sway to a fully staged performance with lifts and flourishes. We'll recommend how many rehearsals you need based on your wedding date and experience, and plan a clear schedule so there's no last-minute stress. Short on time? Our pre-wedding intensive sessions are designed to get you polished and confident in the final weeks. On the day, all you need to do is enjoy the moment.",
  "pages.privatelessons.sections.wedding.cta.label": "Enquire",
  "pages.privatelessons.sections.wedding.gallery.0.alt": "Couple practising a wedding dance",
  "pages.privatelessons.sections.wedding.gallery.1.alt": "Performance lighting in the studio",
  "pages.privatelessons.sections.wedding.gallery.2.alt": "Private lesson for wedding preparation",
  "pages.privatelessons.sections.wedding.title": "First Wedding Dance",
  "pages.shop.hero.overline": "Merchandise",
  "pages.shop.hero.subtitle": "Dancewear, T-shirts, accessories and County Hall merchandise.",
  "pages.shop.hero.title": "Shop",
  "pages.shop.intro": "A Merchandise / Coming Soon page online, with sales also available at the front desk. Categories include dancewear, T-shirts, dance socks, tote and dance bags, water bottles, accessories and gift cards.",
  "pages.shop.meta.description": "Dancewear, merchandise and accessories at County Hall Dance Centre.",
  "pages.shop.meta.title": "Shop",
  "pages.shop.sections.accessories.title": "Accessories",
  "pages.shop.sections.dancewear.title": "Dancewear",
  "pages.shop.sections.merchandise.title": "County Hall Merchandise",
  "pages.shop.sections.t_shirts.title": "T-Shirts",
  "pages.studiohire.overview.cta.body": "Tell us your preferred date, times, space and group size and we'll come back to you with availability.",
  "pages.studiohire.overview.cta.button.label": "Enquire about hire",
  "pages.studiohire.overview.cta.secondary": "Or message us on WeChat: 18518614868 · Instagram: @countyhalldancecentre",
  "pages.studiohire.overview.cta.title": "Plan your booking",
  "pages.studiohire.overview.facilities.extranote": "You are welcome to bring your own equipment, set up and decorate the space, and bring your own catering and drinks.",
  "pages.studiohire.overview.facilities.includednote": "Included in every booking at no extra charge:",
  "pages.studiohire.overview.facilities.items.0": "Tables and chairs",
  "pages.studiohire.overview.facilities.items.1": "Wi-Fi",
  "pages.studiohire.overview.facilities.items.2": "Power sockets",
  "pages.studiohire.overview.facilities.items.3": "Lighting",
  "pages.studiohire.overview.facilities.items.4": "Sound system",
  "pages.studiohire.overview.facilities.items.5": "4 microphones",
  "pages.studiohire.overview.facilities.items.6": "Kitchen",
  "pages.studiohire.overview.facilities.items.7": "Tea and refreshment facilities",
  "pages.studiohire.overview.facilities.items.8": "Toilets",
  "pages.studiohire.overview.facilities.items.9": "Changing rooms",
  "pages.studiohire.overview.facilities.title": "Facilities & equipment",
  "pages.studiohire.overview.facts.items.0": "Approx. 300 m² in total",
  "pages.studiohire.overview.facts.items.1": "4.5 m ceiling height",
  "pages.studiohire.overview.facts.items.2": "Up to 120 guests",
  "pages.studiohire.overview.facts.items.3": "5 minutes' walk from Waterloo and Westminster",
  "pages.studiohire.overview.facts.title": "Key facts",
  "pages.studiohire.overview.gallery.0.alt": "Main studio floor with natural light",
  "pages.studiohire.overview.gallery.1.alt": "Spacious dance studio at County Hall",
  "pages.studiohire.overview.gallery.2.alt": "Studio set up for classes and workshops",
  "pages.studiohire.overview.gallery.3.alt": "Professional dance space on the South Bank",
  "pages.studiohire.overview.hero.image.alt": "Studio space available for hire at County Hall",
  "pages.studiohire.overview.hero.overline": "South Bank studios",
  "pages.studiohire.overview.hero.subtitle": "Two flexible spaces inside London's iconic County Hall — for rehearsals, classes, meetings, filming, parties, exhibitions and live events.",
  "pages.studiohire.overview.hero.title": "Studio Hire",
  "pages.studiohire.overview.howtobook.steps.0.body": "Contact us through this website, our official WeChat (18518614868) or Instagram (@countyhalldancecentre). Please book at least one week in advance.",
  "pages.studiohire.overview.howtobook.steps.0.title": "Enquire",
  "pages.studiohire.overview.howtobook.steps.1.body": "We'll check availability and confirm your date, space and hours.",
  "pages.studiohire.overview.howtobook.steps.1.title": "Confirm",
  "pages.studiohire.overview.howtobook.steps.2.body": "Full payment is due no later than three days before your booking, by bank transfer to our company account.",
  "pages.studiohire.overview.howtobook.steps.2.title": "Pay",
  "pages.studiohire.overview.howtobook.steps.3.body": "Our on-site manager will welcome you and be available throughout your hire.",
  "pages.studiohire.overview.howtobook.steps.3.title": "Arrive",
  "pages.studiohire.overview.howtobook.title": "How to book",
  "pages.studiohire.overview.intro": "Set on the 2nd floor of County Hall on the South Bank, our venue offers around 300 m² of bright, versatile space with 4.5-metre ceilings. Hire the whole venue or book one of our two spaces separately — the 70 m² vinyl-floor studio for classes, rehearsals and smaller sessions, or the 200 m² wooden-floor hall for workshops, performances, parties and larger events. With Waterloo and Westminster stations each just a five-minute walk away, it's easy for your team, cast or guests to reach.",
  "pages.studiohire.overview.meta.description": "Hire a 70 m² vinyl-floor studio or a 200 m² wooden-floor hall at County Hall on the South Bank. From £200 per hour, member rates available.",
  "pages.studiohire.overview.meta.title": "Studio Hire",
  "pages.studiohire.overview.pricing.columns.0": "",
  "pages.studiohire.overview.pricing.columns.1": "Standard rate",
  "pages.studiohire.overview.pricing.columns.2": "Member rate",
  "pages.studiohire.overview.pricing.membershiplink.label": "Learn about membership",
  "pages.studiohire.overview.pricing.notes.0": "Minimum booking: 1 hour.",
  "pages.studiohire.overview.pricing.notes.1": "Bookings are available until 18:00; evening bookings after 18:00 are not available.",
  "pages.studiohire.overview.pricing.notes.2": "Refundable security deposit: £100.",
  "pages.studiohire.overview.pricing.notes.3": "Prices are final — no additional taxes or fees. All equipment is included.",
  "pages.studiohire.overview.pricing.notes.4": "Members of County Hall Dance Centre receive reduced hire rates.",
  "pages.studiohire.overview.pricing.rows.half_day.label": "Half day",
  "pages.studiohire.overview.pricing.rows.half_day.member": "£500",
  "pages.studiohire.overview.pricing.rows.half_day.standard": "£1,000",
  "pages.studiohire.overview.pricing.rows.weekday_per_hour.label": "Weekday, per hour",
  "pages.studiohire.overview.pricing.rows.weekday_per_hour.member": "£100",
  "pages.studiohire.overview.pricing.rows.weekday_per_hour.standard": "£200",
  "pages.studiohire.overview.pricing.rows.weekend_daytime_per_hour.label": "Weekend daytime, per hour",
  "pages.studiohire.overview.pricing.rows.weekend_daytime_per_hour.member": "£150",
  "pages.studiohire.overview.pricing.rows.weekend_daytime_per_hour.standard": "£200",
  "pages.studiohire.overview.pricing.title": "Pricing",
  "pages.studiohire.overview.spaces.items.vinyl_studio.body": "A focused, practical studio with a professional vinyl dance floor — well suited to regular classes, rehearsals, auditions and smaller group sessions.",
  "pages.studiohire.overview.spaces.items.vinyl_studio.floor": "Dance vinyl",
  "pages.studiohire.overview.spaces.items.vinyl_studio.idealfor": "Classes, rehearsals, auditions, small workshops and one-to-one sessions",
  "pages.studiohire.overview.spaces.items.vinyl_studio.size": "70 m²",
  "pages.studiohire.overview.spaces.items.vinyl_studio.title": "Vinyl-Floor Studio",
  "pages.studiohire.overview.spaces.items.wooden_hall.body": "Our largest space, with a wooden floor and generous 4.5-metre ceilings — room to move, perform, present or celebrate with larger groups.",
  "pages.studiohire.overview.spaces.items.wooden_hall.floor": "Wooden floor",
  "pages.studiohire.overview.spaces.items.wooden_hall.idealfor": "Workshops, social dances, performances, parties, exhibitions and corporate events",
  "pages.studiohire.overview.spaces.items.wooden_hall.size": "200 m²",
  "pages.studiohire.overview.spaces.items.wooden_hall.title": "Wooden-Floor Hall",
  "pages.studiohire.overview.spaces.title": "Our spaces",
  "pages.studiohire.overview.suitablefor.items.0": "Meetings",
  "pages.studiohire.overview.suitablefor.items.1": "Training sessions",
  "pages.studiohire.overview.suitablefor.items.2": "Rehearsals",
  "pages.studiohire.overview.suitablefor.items.3": "Classes & workshops",
  "pages.studiohire.overview.suitablefor.items.4": "Photo & film shoots",
  "pages.studiohire.overview.suitablefor.items.5": "Live streams",
  "pages.studiohire.overview.suitablefor.items.6": "Parties & celebrations",
  "pages.studiohire.overview.suitablefor.items.7": "Exhibitions",
  "pages.studiohire.overview.suitablefor.items.8": "Cultural events",
  "pages.studiohire.overview.suitablefor.title": "Suitable for",
  "pages.studiohire.overview.terms.items.0.body": "must be made at least three days before your booking. Cancellations made with less notice are non-refundable.",
  "pages.studiohire.overview.terms.items.0.title": "Cancellations and date changes",
  "pages.studiohire.overview.terms.items.1.body": "must be confirmed at least one day in advance.",
  "pages.studiohire.overview.terms.items.1.title": "Extra time or changes to guest numbers",
  "pages.studiohire.overview.terms.items.2.body": "your £100 deposit is refunded in full after your hire provided there is no damage. Any damage to the venue, furniture or equipment will be charged at cost.",
  "pages.studiohire.overview.terms.items.2.title": "Deposit:",
  "pages.studiohire.overview.terms.items.3.body": "no pets, no smoking, no open flames and no illegal activity. Under-18s are not permitted. Maximum capacity is 120 people.",
  "pages.studiohire.overview.terms.items.3.title": "House rules:",
  "pages.studiohire.overview.terms.items.4.body": "a venue manager is present during every booking.",
  "pages.studiohire.overview.terms.items.4.title": "On-site support:",
  "pages.studiohire.overview.terms.title": "Booking terms",
  "pages.studiohire.subpages.our_space.hero.overline": "Studio Hire",
  "pages.studiohire.subpages.our_space.hero.subtitle": "Main dance and events space with wood floor, dance vinyl, mirrors, barres and flexible seating.",
  "pages.studiohire.subpages.our_space.hero.title": "Our Space",
  "pages.studiohire.subpages.our_space.intro": "Main dance and events space — around 300 m² in total, planned to include approx. 200 m² of wood floor and approx. 60 m² of professional dance vinyl, a mirrored wall, dance barres, a sound system, event lighting, a reception/lounge area and flexible seating.",
  "pages.studiohire.subpages.our_space.meta.description": "Studio space and facilities at County Hall Dance Centre.",
  "pages.studiohire.subpages.our_space.meta.title": "Our Space",
  "pages.studiohire.subpages.our_space.sections.capacity.title": "Capacity",
  "pages.studiohire.subpages.our_space.sections.facilities.title": "Facilities",
  "pages.studiohire.subpages.space_booking.hero.overline": "Studio Hire",
  "pages.studiohire.subpages.space_booking.hero.subtitle": "Tell us your preferred date, activity and group size — we will respond with availability.",
  "pages.studiohire.subpages.space_booking.hero.title": "Space Booking",
  "pages.studiohire.subpages.space_booking.intro": "Enquire via our Studio Hire form or email info@countyhalldancecentre.com. The form collects your preferred date and time, activity type, expected numbers, equipment needs and contact details.",
  "pages.studiohire.subpages.space_booking.meta.description": "Enquire about studio hire at County Hall Dance Centre.",
  "pages.studiohire.subpages.space_booking.meta.title": "Space Booking",
  "pages.studiohire.subpages.space_booking.sections.enquiry_form.title": "Enquiry form",
  "pages.studiohire.subpages.space_booking.sections.how_to_book.title": "How to book",
  "pages.tasterclasses.hero.overline": "Classes",
  "pages.tasterclasses.hero.subtitle": "New to the Centre? Start with a taster and find the class that suits you.",
  "pages.tasterclasses.hero.title": "Taster Classes",
  "pages.tasterclasses.intro": "Taster classes are a low-commitment way to experience our teaching, studio and community before enrolling.",
  "pages.tasterclasses.meta.description": "Try a taster class at County Hall Dance Centre.",
  "pages.tasterclasses.meta.title": "Taster Classes",
  "pages.tasterclasses.sections.available_tasters.title": "Available taster classes",
  "pages.tasterclasses.sections.what_to_bring.title": "What to bring",
  "pages.timetable.booking.description": "Browse this week's classes below. For course enrolment, visit our courses page.",
  "pages.timetable.booking.image.alt": "Class schedule for 14–20 September 2026 at County Hall Dance & Performing Arts School",
  "pages.timetable.booking.placeholderhint": "Replace this container with your ClassForKids, bsport, or other embed code.",
  "pages.timetable.booking.placeholderlabel": "Booking widget placeholder",
  "pages.timetable.booking.providernote": "Real-time booking is handled by our external provider. CHD PAS does not process class payments on this website.",
  "pages.timetable.booking.title": "Class timetable",
  "pages.timetable.helplinks.browse_courses.label": "Browse courses",
  "pages.timetable.helplinks.contact_us.label": "Contact us",
  "pages.timetable.helplinks.frequently_asked_questions.label": "Frequently asked questions",
  "pages.timetable.hero.overline": "Plan your week",
  "pages.timetable.hero.subtitle": "Browse this week's classes by day and style, then reserve your place through our secure booking system.",
  "pages.timetable.hero.title": "Timetable & Booking",
  "pages.timetable.meta.description": "View the weekly class timetable and book your place at County Hall Dance & Performing Arts School.",
  "pages.timetable.meta.title": "Timetable & Booking",
  "pages.timetable.newcomernote": "New to the Centre? Get in touch and we'll help you choose the right class — WeChat: 18518614868.",
  "pages.timetable.trial.body": "Select a suitable class from the timetable below, then choose the trial option at checkout. Our team will welcome you on arrival.",
  "pages.timetable.trial.cta.label": "Book",
  "pages.timetable.trial.overline": "New to CHD PAS?",
  "pages.timetable.trial.title": "Book a taster trial"
} as const;

export type CopyId = keyof typeof copy;
