/** Imported from content/website-copy.csv — do not edit by hand; run: npm run content:import */

export const copy = {
  "meta.defaultdescription": "A refined London dance and performing arts school offering ballet, contemporary, jazz, drama, and more — for every age and stage.",
  "meta.shortname": "CHD PAS",
  "meta.sitename": "County Hall Dance & Performing Arts School",
  "global.utilitybar.email.label": "hello@countyhalldance.co.uk",
  "global.utilitybar.findus.label": "Find us",
  "global.utilitybar.phone.label": "+44 20 7946 0958",
  "global.utilitybar.social.facebook.label": "Follow us on Facebook",
  "global.utilitybar.social.instagram.label": "Follow us on Instagram",
  "global.utilitybar.social.youtube.label": "Watch us on YouTube",
  "global.logo.alt": "County Hall Dance & Performing Arts School",
  "global.logo.nameline1": "County Hall",
  "global.logo.nameline2": "Dance & Performing Arts School",
  "global.navigation.booktrial.label": "Book a Trial",
  "global.navigation.items.about_us.children.about_us.label": "About Us",
  "global.navigation.items.about_us.children.contact.label": "Contact",
  "global.navigation.items.about_us.children.faqs.label": "FAQs",
  "global.navigation.items.about_us.children.gift_cards.label": "Gift Cards",
  "global.navigation.items.about_us.children.join_us.label": "Join Us",
  "global.navigation.items.about_us.children.membership_terms.label": "Membership Terms",
  "global.navigation.items.about_us.label": "About Us",
  "global.navigation.items.classes.children.booking.label": "Booking",
  "global.navigation.items.classes.children.class_descriptions.label": "Class Descriptions",
  "global.navigation.items.classes.children.instructors.label": "Instructors",
  "global.navigation.items.classes.children.taster_classes.label": "Taster Classes",
  "global.navigation.items.classes.children.timetable.label": "Timetable",
  "global.navigation.items.classes.label": "Classes",
  "global.navigation.items.events.children.cross_arts_events.label": "Cross-Arts Events",
  "global.navigation.items.events.children.masterclasses.label": "Masterclasses",
  "global.navigation.items.events.children.milonga.label": "Milonga",
  "global.navigation.items.events.children.performances.label": "Performances",
  "global.navigation.items.events.children.social_dance_nights.label": "Social Dance Nights",
  "global.navigation.items.events.children.workshops.label": "Workshops",
  "global.navigation.items.events.label": "Events",
  "global.navigation.items.membership.children.booking_access.label": "Booking Access",
  "global.navigation.items.membership.children.member_benefits.label": "Member Benefits",
  "global.navigation.items.membership.children.monthly_passes.label": "Monthly Passes",
  "global.navigation.items.membership.label": "Membership",
  "global.navigation.items.private_lessons.children.corporate_events.label": "Corporate Events",
  "global.navigation.items.private_lessons.children.couples_dance.label": "Couples' Dance",
  "global.navigation.items.private_lessons.children.first_wedding_dance.label": "First Wedding Dance",
  "global.navigation.items.private_lessons.children.group_experiences.label": "Group Experiences",
  "global.navigation.items.private_lessons.children.one_to_one_lessons.label": "One-to-One Lessons",
  "global.navigation.items.private_lessons.children.school_organisation_workshops.label": "School / Organisation Workshops",
  "global.navigation.items.private_lessons.label": "Private Lessons",
  "global.navigation.items.shop.children.accessories.label": "Accessories",
  "global.navigation.items.shop.children.county_hall_merchandise.label": "County Hall Merchandise",
  "global.navigation.items.shop.children.dancewear.label": "Dancewear",
  "global.navigation.items.shop.children.t_shirts.label": "T-Shirts",
  "global.navigation.items.shop.label": "Shop",
  "global.navigation.items.studio_hire.children.our_space.label": "Our Space",
  "global.navigation.items.studio_hire.children.space_booking.label": "Space Booking",
  "global.navigation.items.studio_hire.label": "Studio Hire",
  "global.navigation.search.label": "Search",
  "global.navigation.search.placeholder": "Search classes, courses, events…",
  "global.footer.columns.explore.links.classes.label": "Classes",
  "global.footer.columns.explore.links.courses.label": "Courses",
  "global.footer.columns.explore.links.events.label": "Events",
  "global.footer.columns.explore.links.faq.label": "FAQ",
  "global.footer.columns.explore.links.gift_cards.label": "Gift Cards",
  "global.footer.columns.explore.title": "Explore",
  "global.footer.columns.school.links.about_us.label": "About Us",
  "global.footer.columns.school.links.careers.label": "Careers",
  "global.footer.columns.school.links.our_faculty.label": "Our Faculty",
  "global.footer.columns.school.links.private_events.label": "Private Events",
  "global.footer.columns.school.title": "The School",
  "global.footer.contact.address.0": "County Hall Dance Studio",
  "global.footer.contact.address.1": "Belvedere Road",
  "global.footer.contact.address.2": "London SE1 7GP",
  "global.footer.contact.email": "hello@countyhalldance.co.uk",
  "global.footer.contact.phone": "+44 20 7946 0958",
  "global.footer.contact.title": "Visit Us",
  "global.footer.copyright": "© {year} County Hall Dance & Performing Arts School. All rights reserved.",
  "global.footer.intro": "County Hall Dance & Performing Arts School nurtures confidence, artistry, and joy through exceptional training in the heart of London.",
  "global.footer.legal.cookie_policy.label": "Cookie Policy",
  "global.footer.legal.privacy_policy.label": "Privacy Policy",
  "global.footer.legal.safeguarding.label": "Safeguarding",
  "global.footer.legal.terms_conditions.label": "Terms & Conditions",
  "global.footer.newsletter.description": "Occasional news on classes, masterclasses, and performances.",
  "global.footer.newsletter.placeholder": "Your email address",
  "global.footer.newsletter.privacynote": "We respect your privacy. Unsubscribe anytime.",
  "global.footer.newsletter.submitlabel": "Subscribe",
  "global.footer.newsletter.title": "Stay in touch",
  "home.hero.nextlabel": "Next",
  "home.hero.previouslabel": "Previous",
  "home.hero.slides.hero_classes.blurb": "Explore adult classes in Contemporary, Chinese Dance, Tango, Yoga and Tai Chi.",
  "home.hero.slides.hero_classes.cta.label": "View Classes",
  "home.hero.slides.hero_classes.headline": "Classes",
  "home.hero.slides.hero_classes.image.alt": "Adult dance class at County Hall Dance Centre",
  "home.hero.slides.hero_events.blurb": "Milongas, themed social nights, masterclasses and cross-arts events.",
  "home.hero.slides.hero_events.cta.label": "View Events",
  "home.hero.slides.hero_events.headline": "Events",
  "home.hero.slides.hero_events.image.alt": "Social dance night at County Hall Dance Centre",
  "home.hero.slides.hero_intro.blurb": "Dance, movement and creative experiences at London's iconic County Hall on the South Bank — classes, workshops and events for adults of every background and level of experience.",
  "home.hero.slides.hero_intro.cta.label": "Explore Classes",
  "home.hero.slides.hero_intro.headline": "Discover dance, movement and creative experiences at London's iconic County Hall.",
  "home.hero.slides.hero_intro.image.alt": "County Hall Dance Centre on the South Bank",
  "home.hero.slides.hero_membership.blurb": "A more flexible way to keep dancing, join events and belong to the community.",
  "home.hero.slides.hero_membership.cta.label": "Membership",
  "home.hero.slides.hero_membership.headline": "Membership",
  "home.hero.slides.hero_membership.image.alt": "Members enjoying a class at County Hall Dance Centre",
  "home.hero.slides.hero_private_lessons.blurb": "Tailored sessions for individuals, couples, wedding first dances and small groups.",
  "home.hero.slides.hero_private_lessons.cta.label": "Enquire",
  "home.hero.slides.hero_private_lessons.headline": "Private Lessons & Experiences",
  "home.hero.slides.hero_private_lessons.image.alt": "Private dance lesson at County Hall Dance Centre",
  "home.hero.slides.hero_studio_hire.blurb": "A South Bank space for dance, theatre and film rehearsals, castings, workshops and events.",
  "home.hero.slides.hero_studio_hire.cta.label": "Studio Hire",
  "home.hero.slides.hero_studio_hire.headline": "Studio Hire",
  "home.hero.slides.hero_studio_hire.image.alt": "Studio space available for hire at County Hall",
  "home.quickactions.items.book_a_class.description": "View the weekly timetable and reserve your place.",
  "home.quickactions.items.book_a_class.label": "Book a Class",
  "home.quickactions.items.book_a_course.description": "Term-length programmes with clear progression.",
  "home.quickactions.items.book_a_course.label": "Book an Event",
  "home.quickactions.items.free_trial.description": "Try a class with no obligation — we welcome newcomers.",
  "home.quickactions.items.free_trial.label": "Free Trial",
  "home.quickactions.linksuffix": "Learn more →",
  "home.quickactions.overline": "Get started",
  "home.events.items.contemporary_intensive_maya_chen.booknow.label": "Book Now",
  "home.events.items.contemporary_intensive_maya_chen.date": "Saturday 18 October 2026",
  "home.events.items.contemporary_intensive_maya_chen.image.alt": "Contemporary dance intensive workshop",
  "home.events.items.contemporary_intensive_maya_chen.location": "Studio A",
  "home.events.items.contemporary_intensive_maya_chen.title": "Contemporary Intensive with Maya Chen",
  "home.events.items.junior_ballet_masterclass.booknow.label": "Book Now",
  "home.events.items.junior_ballet_masterclass.date": "Sunday 26 October 2026",
  "home.events.items.junior_ballet_masterclass.image.alt": "Junior ballet masterclass in progress",
  "home.events.items.junior_ballet_masterclass.location": "Studio B",
  "home.events.items.junior_ballet_masterclass.title": "Junior Ballet Masterclass",
  "home.events.items.musical_theatre_workshop_day.booknow.label": "Book Now",
  "home.events.items.musical_theatre_workshop_day.date": "Saturday 8 November 2026",
  "home.events.items.musical_theatre_workshop_day.image.alt": "Musical theatre workshop participants on stage",
  "home.events.items.musical_theatre_workshop_day.location": "Main Hall",
  "home.events.items.musical_theatre_workshop_day.title": "Musical Theatre Workshop Day",
  "home.events.items.winter_showcase.booknow.label": "Book Now",
  "home.events.items.winter_showcase.date": "Friday 12 December 2026",
  "home.events.items.winter_showcase.image.alt": "Winter showcase performance lighting",
  "home.events.items.winter_showcase.location": "County Hall Theatre",
  "home.events.items.winter_showcase.title": "Winter Showcase — Tickets On Sale",
  "home.events.overline": "What's on",
  "home.events.title": "Upcoming masterclasses & events",
  "home.events.viewall.label": "View all events →",
  "home.classstyles.items.chinese_dance.image.alt": "Chinese dance class",
  "home.classstyles.items.chinese_dance.name": "Chinese Dance",
  "home.classstyles.items.contemporary.image.alt": "Contemporary dance class",
  "home.classstyles.items.contemporary.name": "Contemporary",
  "home.classstyles.items.tai_chi.image.alt": "Tai Chi class",
  "home.classstyles.items.tai_chi.name": "Tai Chi",
  "home.classstyles.items.tango.image.alt": "Tango class",
  "home.classstyles.items.tango.name": "Tango",
  "home.classstyles.items.yoga.image.alt": "Yoga class",
  "home.classstyles.items.yoga.name": "Yoga",
  "home.classstyles.overline": "Our disciplines",
  "home.classstyles.subtitle": "Adult classes in Contemporary, Chinese Dance, Tango, Yoga and Tai Chi — beginners welcome.",
  "home.classstyles.title": "Class styles",
  "home.aboutteaser.body.0": "Founded at the historic County Hall, our school brings together rigorous technical training and a deeply supportive community.",
  "home.aboutteaser.body.1": "Whether you are taking your first plié or preparing for vocational study, our faculty guides every student with patience and precision.",
  "home.aboutteaser.cta.label": "About the school",
  "home.aboutteaser.image.alt": "Students and teachers in the County Hall studio corridor",
  "home.aboutteaser.overline": "Our story",
  "home.aboutteaser.title": "Rooted in London, reaching for excellence",
  "home.privateevents.body": "Host an unforgettable birthday, hen party, or team celebration in our beautiful studios. Choose a theme, bring your guests, and leave the choreography to us.",
  "home.privateevents.cta.label": "Enquire",
  "home.privateevents.image.alt": "Private dance party celebration in studio",
  "home.privateevents.overline": "Celebrate with us",
  "home.privateevents.title": "Private events & parties",
  "home.newsletter.description": "Follow our journey and receive curated updates on classes, performances, and exclusive offers.",
  "home.newsletter.overline": "Join our circle",
  "home.newsletter.placeholder": "Email address",
  "home.newsletter.socialheading": "Connect with us",
  "home.newsletter.submitlabel": "Sign up",
  "home.newsletter.title": "Newsletter & social",
  "pages.common.eventdetailslink": "Details →",
  "pages.common.viewcourselink": "View course →",
  "pages.studiohire.overview.hero.overline": "South Bank studios",
  "pages.studiohire.overview.hero.subtitle": "A multi-purpose space for classes, rehearsals, workshops, social dances, cultural events and private hire.",
  "pages.studiohire.overview.hero.title": "Studio Hire",
  "pages.studiohire.overview.intro": "A flexible, multi-purpose dance and performing-arts space of around 300 m² (first phase), suitable for regular classes, rehearsals, workshops, social dances, cultural events and private hire.",
  "pages.studiohire.overview.meta.description": "Hire a flexible dance and performing-arts space at County Hall on the South Bank.",
  "pages.studiohire.overview.meta.title": "Studio Hire",
  "pages.studiohire.overview.sections.enquiries.title": "Booking & enquiries",
  "pages.studiohire.overview.sections.pricing.title": "Pricing",
  "pages.studiohire.overview.sections.space.title": "Space & facilities",
  "pages.studiohire.subpages.our_space.hero.overline": "Studio Hire",
  "pages.studiohire.subpages.our_space.hero.subtitle": "Main dance and events space with wood floor, dance vinyl, mirrors, barres and flexible seating.",
  "pages.studiohire.subpages.our_space.hero.title": "Our Space",
  "pages.studiohire.subpages.our_space.intro": "Main dance and events space — around 300 m² in total, planned to include approx. 200 m² of wood floor and approx. 60 m² of professional dance vinyl, a mirrored wall, dance barres, a sound system, event lighting, a reception/lounge area and flexible seating.",
  "pages.studiohire.subpages.our_space.meta.description": "Studio space and facilities at County Hall Dance Centre.",
  "pages.studiohire.subpages.our_space.meta.title": "Our Space",
  "pages.studiohire.subpages.our_space.sections.capacity.title": "Capacity",
  "pages.studiohire.subpages.our_space.sections.facilities.title": "Facilities",
  "pages.studiohire.subpages.space_booking.hero.overline": "Studio Hire",
  "pages.studiohire.subpages.space_booking.hero.subtitle": "Tell us your preferred date, activity and group size — we will respond with availability.",
  "pages.studiohire.subpages.space_booking.hero.title": "Space Booking",
  "pages.studiohire.subpages.space_booking.intro": "Enquire via our Studio Hire form or email info@countyhalldancecentre.com. The form collects your preferred date and time, activity type, expected numbers, equipment needs and contact details.",
  "pages.studiohire.subpages.space_booking.meta.description": "Enquire about studio hire at County Hall Dance Centre.",
  "pages.studiohire.subpages.space_booking.meta.title": "Space Booking",
  "pages.studiohire.subpages.space_booking.sections.enquiry_form.title": "Enquiry form",
  "pages.studiohire.subpages.space_booking.sections.how_to_book.title": "How to book",
  "pages.classes.cta.label": "View timetable",
  "pages.classes.detaillabels.agegroups": "Age groups",
  "pages.classes.detaillabels.backlink": "← Classes",
  "pages.classes.hero.overline": "Find your style",
  "pages.classes.hero.subtitle": "Adult dance and movement classes for every background and level — beginners welcome.",
  "pages.classes.hero.title": "Classes",
  "pages.classes.intro": "Explore adult classes in Contemporary, Chinese Dance, Tango, Yoga and Tai Chi. Every class is clearly labelled Beginner, Open Level or Intermediate.",
  "pages.classes.meta.description": "Adult classes in Contemporary, Chinese Dance, Tango, Yoga and Tai Chi at County Hall Dance Centre.",
  "pages.classes.meta.title": "Classes",
  "pages.classes.styles.chinese_dance.agegroups.adults.description": "Designed for adult learners at every stage.",
  "pages.classes.styles.chinese_dance.agegroups.adults.label": "Adults",
  "pages.classes.styles.chinese_dance.cta.label": "Book a class",
  "pages.classes.styles.chinese_dance.hero.image.alt": "Chinese dance class",
  "pages.classes.styles.chinese_dance.hero.overline": "Grace & line",
  "pages.classes.styles.chinese_dance.hero.subtitle": "Classical Chinese dance to build body control, flexibility and stage presence.",
  "pages.classes.styles.chinese_dance.hero.title": "Chinese Dance",
  "pages.classes.styles.chinese_dance.highlights.0.description": "Discover the artistry of classical Chinese movement.",
  "pages.classes.styles.chinese_dance.highlights.0.title": "Cultural expression",
  "pages.classes.styles.chinese_dance.highlights.1.description": "Develop line, poise and body awareness.",
  "pages.classes.styles.chinese_dance.highlights.1.title": "Flexibility & control",
  "pages.classes.styles.chinese_dance.highlights.2.description": "Beginners welcome — check the level on each class.",
  "pages.classes.styles.chinese_dance.highlights.2.title": "All levels",
  "pages.classes.styles.chinese_dance.intro.0": "Blending the grace, line and cultural expression of classical Chinese dance to build body control, flexibility and stage presence.",
  "pages.classes.styles.chinese_dance.metadescription": "Chinese dance classes blending classical grace, line and cultural expression for adults.",
  "pages.classes.styles.chinese_dance.name": "Chinese Dance",
  "pages.classes.styles.contemporary.agegroups.adults.description": "Open to all backgrounds — no dance experience needed.",
  "pages.classes.styles.contemporary.agegroups.adults.label": "Adults",
  "pages.classes.styles.contemporary.cta.label": "Book a class",
  "pages.classes.styles.contemporary.hero.image.alt": "Contemporary dance class",
  "pages.classes.styles.contemporary.hero.overline": "Modern dance",
  "pages.classes.styles.contemporary.hero.subtitle": "Develop coordination, strength and creativity through flow, space and physical expression.",
  "pages.classes.styles.contemporary.hero.title": "Contemporary",
  "pages.classes.styles.contemporary.highlights.0.description": "Explore space, dynamics and personal expression.",
  "pages.classes.styles.contemporary.highlights.0.title": "Creative movement",
  "pages.classes.styles.contemporary.highlights.1.description": "Build physical confidence through structured practice.",
  "pages.classes.styles.contemporary.highlights.1.title": "Strength & coordination",
  "pages.classes.styles.contemporary.highlights.2.description": "Classes labelled Beginner, Open Level or Intermediate.",
  "pages.classes.styles.contemporary.highlights.2.title": "All levels",
  "pages.classes.styles.contemporary.intro.0": "Develop coordination, strength and creativity through flow, space and physical expression.",
  "pages.classes.styles.contemporary.intro.1": "Ideal for adults keen to explore the language of modern dance.",
  "pages.classes.styles.contemporary.metadescription": "Contemporary dance classes for adults at County Hall Dance Centre — flow, space and physical expression.",
  "pages.classes.styles.contemporary.name": "Contemporary",
  "pages.classes.styles.tai_chi.agegroups.adults.description": "Suitable for every age and fitness level.",
  "pages.classes.styles.tai_chi.agegroups.adults.label": "Adults",
  "pages.classes.styles.tai_chi.cta.label": "Book a class",
  "pages.classes.styles.tai_chi.hero.image.alt": "Tai Chi class",
  "pages.classes.styles.tai_chi.hero.overline": "Flow & balance",
  "pages.classes.styles.tai_chi.hero.subtitle": "Cultivate balance, relaxation and body awareness through slow, flowing movement.",
  "pages.classes.styles.tai_chi.hero.title": "Tai Chi",
  "pages.classes.styles.tai_chi.highlights.0.description": "Slow, intentional movement for calm and focus.",
  "pages.classes.styles.tai_chi.highlights.0.title": "Mind-body practice",
  "pages.classes.styles.tai_chi.highlights.1.description": "Develop stability and gentle strength.",
  "pages.classes.styles.tai_chi.highlights.1.title": "Balance & awareness",
  "pages.classes.styles.tai_chi.highlights.2.description": "Welcoming to complete beginners.",
  "pages.classes.styles.tai_chi.highlights.2.title": "All levels",
  "pages.classes.styles.tai_chi.intro.0": "Cultivate balance, relaxation and body awareness through slow, flowing movement, breath and shifts of weight.",
  "pages.classes.styles.tai_chi.metadescription": "Tai Chi classes for adults — balance, relaxation and body awareness.",
  "pages.classes.styles.tai_chi.name": "Tai Chi",
  "pages.classes.styles.tango.agegroups.adults.description": "No partner or experience required to begin.",
  "pages.classes.styles.tango.agegroups.adults.label": "Adults",
  "pages.classes.styles.tango.cta.label": "Book a class",
  "pages.classes.styles.tango.hero.image.alt": "Tango class",
  "pages.classes.styles.tango.hero.overline": "Connection & musicality",
  "pages.classes.styles.tango.hero.subtitle": "Learn lead and follow, musicality and the etiquette of social dance.",
  "pages.classes.styles.tango.hero.title": "Tango",
  "pages.classes.styles.tango.highlights.0.description": "Lead, follow and floor etiquette from day one.",
  "pages.classes.styles.tango.highlights.0.title": "Social dance skills",
  "pages.classes.styles.tango.highlights.1.description": "Move with confidence to live and recorded tango music.",
  "pages.classes.styles.tango.highlights.1.title": "Musicality",
  "pages.classes.styles.tango.highlights.2.description": "Join our social dance nights and themed events.",
  "pages.classes.styles.tango.highlights.2.title": "Milongas & events",
  "pages.classes.styles.tango.intro.0": "Learn connection, lead and follow, musicality and the etiquette of social dance, building confidence from the very first steps.",
  "pages.classes.styles.tango.metadescription": "Tango classes for adults — connection, musicality and social dance etiquette.",
  "pages.classes.styles.tango.name": "Tango",
  "pages.classes.styles.yoga.agegroups.adults.description": "Open to beginners and returning practitioners.",
  "pages.classes.styles.yoga.agegroups.adults.label": "Adults",
  "pages.classes.styles.yoga.cta.label": "Book a class",
  "pages.classes.styles.yoga.hero.image.alt": "Yoga class",
  "pages.classes.styles.yoga.hero.overline": "Breath & stretch",
  "pages.classes.styles.yoga.hero.subtitle": "Improve flexibility and overall wellbeing through breath, stretch and focused practice.",
  "pages.classes.styles.yoga.hero.title": "Yoga",
  "pages.classes.styles.yoga.highlights.0.description": "Stretch, breathe and restore balance.",
  "pages.classes.styles.yoga.highlights.0.title": "Wellbeing focus",
  "pages.classes.styles.yoga.highlights.1.description": "A calm, focused environment for every body.",
  "pages.classes.styles.yoga.highlights.1.title": "Music-guided practice",
  "pages.classes.styles.yoga.highlights.2.description": "Check class information for level and format details.",
  "pages.classes.styles.yoga.highlights.2.title": "All levels",
  "pages.classes.styles.yoga.intro.0": "Improve flexibility and overall wellbeing through breath, stretch and focused, music-guided practice.",
  "pages.classes.styles.yoga.metadescription": "Yoga classes for adults — flexibility, breath and wellbeing at County Hall Dance Centre.",
  "pages.classes.styles.yoga.name": "Yoga",
  "pages.classesinfo.hero.overline": "Classes",
  "pages.classesinfo.hero.subtitle": "Explore our adult dance and movement programme and meet the teaching team.",
  "pages.classesinfo.hero.title": "Class Descriptions & Instructors",
  "pages.classesinfo.intro": "Every class is clearly labelled Beginner, Open Level or Intermediate. Beginners welcome — no dance experience needed.",
  "pages.classesinfo.meta.description": "Class descriptions and instructor profiles for adult classes at County Hall Dance Centre.",
  "pages.classesinfo.meta.title": "Class Descriptions & Instructors",
  "pages.classesinfo.sections.descriptions.title": "Class Descriptions",
  "pages.classesinfo.sections.instructors.title": "Instructors",
  "pages.classbooking.hero.overline": "Classes",
  "pages.classbooking.hero.subtitle": "View live availability and reserve your place through our booking partner.",
  "pages.classbooking.hero.title": "Booking",
  "pages.classbooking.intro": "Choose a class from the timetable and follow the booking link. Advance booking is recommended.",
  "pages.classbooking.meta.description": "Book adult dance and movement classes at County Hall Dance Centre.",
  "pages.classbooking.meta.title": "Class Booking",
  "pages.classbooking.sections.how_to_book.title": "How to book",
  "pages.classbooking.sections.policies.title": "Booking policies",
  "pages.tasterclasses.hero.overline": "Classes",
  "pages.tasterclasses.hero.subtitle": "New to the Centre? Start with a taster and find the class that suits you.",
  "pages.tasterclasses.hero.title": "Taster Classes",
  "pages.tasterclasses.intro": "Taster classes are a low-commitment way to experience our teaching, studio and community before enrolling.",
  "pages.tasterclasses.meta.description": "Try a taster class at County Hall Dance Centre.",
  "pages.tasterclasses.meta.title": "Taster Classes",
  "pages.tasterclasses.sections.available_tasters.title": "Available taster classes",
  "pages.tasterclasses.sections.what_to_bring.title": "What to bring",
  "pages.timetable.booking.description": "Browse this week's classes below. For course enrolment, visit our courses page.",
  "pages.timetable.booking.image.alt": "Class schedule for 14–20 September 2026 at County Hall Dance & Performing Arts School",
  "pages.timetable.booking.placeholderhint": "Replace this container with your ClassForKids, bsport, or other embed code.",
  "pages.timetable.booking.placeholderlabel": "Booking widget placeholder",
  "pages.timetable.booking.providernote": "Real-time booking is handled by our external provider. CHD PAS does not process class payments on this website.",
  "pages.timetable.booking.title": "Class timetable",
  "pages.timetable.helplinks.browse_courses.label": "Browse courses",
  "pages.timetable.helplinks.contact_us.label": "Contact us",
  "pages.timetable.helplinks.frequently_asked_questions.label": "Frequently asked questions",
  "pages.timetable.hero.overline": "Plan your week",
  "pages.timetable.hero.subtitle": "Browse classes by day and age group, then reserve through our secure booking partner.",
  "pages.timetable.hero.title": "Timetable & Booking",
  "pages.timetable.meta.description": "View the weekly class timetable and book your place at County Hall Dance & Performing Arts School.",
  "pages.timetable.meta.title": "Timetable & Booking",
  "pages.timetable.trial.body": "Select a suitable class from the timetable below, then choose the trial option at checkout. Our team will welcome you on arrival.",
  "pages.timetable.trial.cta.label": "Book",
  "pages.timetable.trial.overline": "New to CHD PAS?",
  "pages.timetable.trial.title": "Book a taster trial",
  "pages.courses.detaillabels.backlink": "← All courses",
  "pages.courses.detaillabels.duration": "Duration",
  "pages.courses.detaillabels.includes": "What's included",
  "pages.courses.detaillabels.price": "Price",
  "pages.courses.detaillabels.schedule": "Schedule",
  "pages.courses.hero.overline": "Structured progression",
  "pages.courses.hero.subtitle": "Immersive term programmes designed to deepen technique, artistry, and performance readiness.",
  "pages.courses.hero.title": "Courses",
  "pages.courses.intro": "Courses differ from drop-in classes — they follow a curated syllabus across a full term, culminating in an informal sharing or assessment where appropriate.",
  "pages.courses.items.adult_ballet_open.cta.label": "Enrol via timetable",
  "pages.courses.items.adult_ballet_open.description.0": "Rebuild strength and grace at the barre and in centre, with modifications offered throughout.",
  "pages.courses.items.adult_ballet_open.description.1": "Each block introduces new enchaînements while revisiting core principles.",
  "pages.courses.items.adult_ballet_open.duration": "6-week blocks",
  "pages.courses.items.adult_ballet_open.excerpt": "A welcoming ballet class for adults — beginners and returners alike.",
  "pages.courses.items.adult_ballet_open.image.alt": "Adult ballet open course",
  "pages.courses.items.adult_ballet_open.includes.0": "Weekly 75-minute class",
  "pages.courses.items.adult_ballet_open.includes.1": "Technique notes via email",
  "pages.courses.items.adult_ballet_open.includes.2": "Optional end-of-block class video",
  "pages.courses.items.adult_ballet_open.level": "All levels",
  "pages.courses.items.adult_ballet_open.metadescription": "Open-level adult ballet course at CHD PAS, London.",
  "pages.courses.items.adult_ballet_open.price": "£96 per block",
  "pages.courses.items.adult_ballet_open.schedule": "Mondays, 19:00 – 20:15",
  "pages.courses.items.adult_ballet_open.term": "Rolling enrolment",
  "pages.courses.items.adult_ballet_open.title": "Adult Ballet Open",
  "pages.courses.items.junior_ballet_foundation.cta.label": "Enrol via timetable",
  "pages.courses.items.junior_ballet_foundation.description.0": "This course introduces young dancers to the fundamentals of ballet posture, port de bras, and basic allegro.",
  "pages.courses.items.junior_ballet_foundation.description.1": "Classes are taught in a nurturing environment with clear expectations and plenty of encouragement.",
  "pages.courses.items.junior_ballet_foundation.duration": "12 weeks",
  "pages.courses.items.junior_ballet_foundation.excerpt": "A twelve-week introduction to classical ballet for ages 6–9.",
  "pages.courses.items.junior_ballet_foundation.image.alt": "Junior ballet foundation course",
  "pages.courses.items.junior_ballet_foundation.includes.0": "Weekly 60-minute class",
  "pages.courses.items.junior_ballet_foundation.includes.1": "Course handbook and practice notes",
  "pages.courses.items.junior_ballet_foundation.includes.2": "End-of-term studio sharing",
  "pages.courses.items.junior_ballet_foundation.level": "Beginner – Elementary",
  "pages.courses.items.junior_ballet_foundation.metadescription": "Twelve-week junior ballet foundation course for ages 6–9 at CHD PAS.",
  "pages.courses.items.junior_ballet_foundation.price": "£168 per term",
  "pages.courses.items.junior_ballet_foundation.schedule": "Saturdays, 10:00 – 11:00",
  "pages.courses.items.junior_ballet_foundation.term": "Autumn Term 2026",
  "pages.courses.items.junior_ballet_foundation.title": "Junior Ballet Foundation",
  "pages.courses.items.musical_theatre_performance.cta.label": "Enrol via timetable",
  "pages.courses.items.musical_theatre_performance.description.0": "Sing, dance, and act your way through a selected musical number, rehearsed for a small invited audience.",
  "pages.courses.items.musical_theatre_performance.description.1": "Vocal coaching and ensemble work are integrated throughout the term.",
  "pages.courses.items.musical_theatre_performance.duration": "14 weeks",
  "pages.courses.items.musical_theatre_performance.excerpt": "Triple-threat training culminating in a staged musical excerpt.",
  "pages.courses.items.musical_theatre_performance.image.alt": "Musical theatre performance course",
  "pages.courses.items.musical_theatre_performance.includes.0": "Weekly 3-hour session",
  "pages.courses.items.musical_theatre_performance.includes.1": "Vocal warm-up resources",
  "pages.courses.items.musical_theatre_performance.includes.2": "Costume hire for final sharing",
  "pages.courses.items.musical_theatre_performance.level": "Intermediate – Advanced",
  "pages.courses.items.musical_theatre_performance.metadescription": "Musical theatre performance course for intermediate and advanced students.",
  "pages.courses.items.musical_theatre_performance.price": "£320 per term",
  "pages.courses.items.musical_theatre_performance.schedule": "Saturdays, 13:00 – 16:00",
  "pages.courses.items.musical_theatre_performance.term": "Spring Term 2027",
  "pages.courses.items.musical_theatre_performance.title": "Musical Theatre Performance",
  "pages.courses.items.teen_contemporary_intensive.cta.label": "Enrol via timetable",
  "pages.courses.items.teen_contemporary_intensive.description.0": "Students explore release technique, contact principles, and choreographic tasks across a focused ten-week block.",
  "pages.courses.items.teen_contemporary_intensive.description.1": "The course prepares dancers for school showcases and optional audition pieces.",
  "pages.courses.items.teen_contemporary_intensive.duration": "10 weeks",
  "pages.courses.items.teen_contemporary_intensive.excerpt": "Develop contemporary technique, improvisation, and performance skills.",
  "pages.courses.items.teen_contemporary_intensive.image.alt": "Teen contemporary intensive course",
  "pages.courses.items.teen_contemporary_intensive.includes.0": "Weekly 90-minute class",
  "pages.courses.items.teen_contemporary_intensive.includes.1": "Guest artist Q&A session",
  "pages.courses.items.teen_contemporary_intensive.includes.2": "Performance workshop",
  "pages.courses.items.teen_contemporary_intensive.level": "Intermediate",
  "pages.courses.items.teen_contemporary_intensive.metadescription": "Intermediate contemporary course for teens at County Hall Dance.",
  "pages.courses.items.teen_contemporary_intensive.price": "£195 per term",
  "pages.courses.items.teen_contemporary_intensive.schedule": "Wednesdays, 17:30 – 19:00",
  "pages.courses.items.teen_contemporary_intensive.term": "Autumn Term 2026",
  "pages.courses.items.teen_contemporary_intensive.title": "Teen Contemporary Intensive",
  "pages.courses.meta.description": "Term-length dance and performing arts courses with structured progression at CHD PAS.",
  "pages.courses.meta.title": "Courses",
  "pages.membership.subpages.booking_access.hero.overline": "Membership",
  "pages.membership.subpages.booking_access.hero.subtitle": "How members reserve classes and events through our booking system.",
  "pages.membership.subpages.booking_access.hero.title": "Booking Access",
  "pages.membership.subpages.booking_access.intro": "Members will receive booking access through our online timetable and companion app — details to follow via our app partner.",
  "pages.membership.subpages.booking_access.meta.description": "Member booking access at County Hall Dance Centre.",
  "pages.membership.subpages.booking_access.meta.title": "Booking Access",
  "pages.membership.subpages.booking_access.sections.member_booking.title": "Member booking",
  "pages.membership.subpages.booking_access.sections.support.title": "Support",
  "pages.membership.subpages.member_benefits.hero.overline": "Membership",
  "pages.membership.subpages.member_benefits.hero.subtitle": "A more flexible way to keep dancing, join events and belong to the community.",
  "pages.membership.subpages.member_benefits.hero.title": "Member Benefits",
  "pages.membership.subpages.member_benefits.intro": "Membership offers ongoing access to classes, events and community benefits — details to be confirmed before launch.",
  "pages.membership.subpages.member_benefits.meta.description": "Benefits of membership at County Hall Dance Centre.",
  "pages.membership.subpages.member_benefits.meta.title": "Member Benefits",
  "pages.membership.subpages.member_benefits.sections.benefits.title": "What's included",
  "pages.membership.subpages.member_benefits.sections.how_to_join.title": "How to join",
  "pages.membership.subpages.monthly_passes.hero.overline": "Membership",
  "pages.membership.subpages.monthly_passes.hero.subtitle": "Flexible monthly options for regular class attendance.",
  "pages.membership.subpages.monthly_passes.hero.title": "Monthly Passes",
  "pages.membership.subpages.monthly_passes.intro": "Monthly passes will be published with validity, cancellation policy and transferability before online booking opens.",
  "pages.membership.subpages.monthly_passes.meta.description": "Monthly pass options at County Hall Dance Centre.",
  "pages.membership.subpages.monthly_passes.meta.title": "Monthly Passes",
  "pages.membership.subpages.monthly_passes.sections.pass_options.title": "Pass options",
  "pages.membership.subpages.monthly_passes.sections.terms.title": "Terms",
  "pages.membershipterms.hero.overline": "About Us",
  "pages.membershipterms.hero.subtitle": "Terms governing membership passes, booking access and cancellation.",
  "pages.membershipterms.hero.title": "Membership Terms",
  "pages.membershipterms.intro": "Final membership terms, including validity, cancellation policy and transferability, will be published before online booking opens.",
  "pages.membershipterms.meta.description": "Membership terms and conditions at County Hall Dance Centre.",
  "pages.membershipterms.meta.title": "Membership Terms",
  "pages.membershipterms.sections.cancellation.title": "Cancellation policy",
  "pages.membershipterms.sections.general.title": "General terms",
  "pages.privatelessons.hero.overline": "Tailored for you",
  "pages.privatelessons.hero.subtitle": "One-to-one lessons, couples' dance, wedding first dances, group experiences, corporate events and school workshops.",
  "pages.privatelessons.hero.title": "Private Lessons & Experiences",
  "pages.privatelessons.intro": "Services include private dance lessons; dance experiences for individuals, couples and groups; wedding first dances; corporate team experiences; school and organisation workshops; rehearsals, auditions, filming and private events; and Milonga and social dance events.",
  "pages.privatelessons.meta.description": "Private dance lessons and bespoke experiences at County Hall Dance Centre.",
  "pages.privatelessons.meta.title": "Private Lessons & Experiences",
  "pages.privatelessons.sections.corporate.title": "Corporate Events",
  "pages.privatelessons.sections.couples.title": "Couples' Dance",
  "pages.privatelessons.sections.groups.title": "Group Experiences",
  "pages.privatelessons.sections.one_to_one.title": "One-to-One Lessons",
  "pages.privatelessons.sections.schools.title": "School / Organisation Workshops",
  "pages.privatelessons.sections.wedding.title": "First Wedding Dance",
  "pages.shop.hero.overline": "Merchandise",
  "pages.shop.hero.subtitle": "Dancewear, T-shirts, accessories and County Hall merchandise.",
  "pages.shop.hero.title": "Shop",
  "pages.shop.intro": "A Merchandise / Coming Soon page online, with sales also available at the front desk. Categories include dancewear, T-shirts, dance socks, tote and dance bags, water bottles, accessories and gift cards.",
  "pages.shop.meta.description": "Dancewear, merchandise and accessories at County Hall Dance Centre.",
  "pages.shop.meta.title": "Shop",
  "pages.shop.sections.accessories.title": "Accessories",
  "pages.shop.sections.dancewear.title": "Dancewear",
  "pages.shop.sections.merchandise.title": "County Hall Merchandise",
  "pages.shop.sections.t_shirts.title": "T-Shirts",
  "pages.about.cta.body": "We would love to welcome you for a trial class or a tour of the studios.",
  "pages.about.cta.button.label": "Get in touch",
  "pages.about.cta.title": "Visit us",
  "pages.about.faculty.intro": "Our teachers are working artists and experienced educators, selected for both technical expertise and pastoral care.",
  "pages.about.faculty.members.faculty_kiki.bio": "A highly experienced choreographer and large-scale performance director, Kiki shapes the Centre's artistic programme and its connection between dance, music, visual art and culture.",
  "pages.about.faculty.members.faculty_kiki.image.alt": "Kiki",
  "pages.about.faculty.members.faculty_kiki.name": "Kiki",
  "pages.about.faculty.members.faculty_kiki.role": "Company Director and Artistic Director",
  "pages.about.faculty.members.faculty_michael.bio": "Michael brings extensive international film, television and production-management experience, leading operations, partnerships, communications and business development.",
  "pages.about.faculty.members.faculty_michael.image.alt": "Michael",
  "pages.about.faculty.members.faculty_michael.name": "Michael",
  "pages.about.faculty.members.faculty_michael.role": "Company Director and Management and Marketing Lead",
  "pages.about.faculty.overline": "Meet the team",
  "pages.about.faculty.title": "Our faculty",
  "pages.about.hero.image.alt": "County Hall Dance studio",
  "pages.about.hero.overline": "Our school",
  "pages.about.hero.subtitle": "Discover dance, movement and creative experiences at London's iconic County Hall",
  "pages.about.hero.title": "About County Hall Dance & Performing Arts School",
  "pages.about.meta.description": "Learn about County Hall Dance & Performing Arts School — our history, values, and faculty.",
  "pages.about.meta.title": "About Us",
  "pages.about.story.paragraphs.0": "County Hall Dance Centre is a new home for dance, movement and creativity in the heart of London. Located inside the iconic County Hall on the South Bank, the Centre brings together the best dance classes, workshops, social dances, private experiences and special events. More than a dance studio, it is a welcoming creative community where people can move, learn, connect and enjoy the arts together.",
  "pages.about.story.title": "Our story",
  "pages.about.values.items.0.description": "To make high-quality dance and mind-body classes open, welcoming, and connected in the heart of London.",
  "pages.about.values.items.0.title": "Mission",
  "pages.about.values.items.1.description": "To grow from a dedicated professional dance space into a creative destination that brings together dance, performing arts, music, visual arts, and international cultural exchange.",
  "pages.about.values.items.1.title": "Vision",
  "pages.about.values.items.2.description": "Move. Create. Connect. Belong. — helping adults of every background and level of experience build confidence, wellbeing, and a sense of belonging through the arts.",
  "pages.about.values.items.2.title": "Philosophy",
  "pages.about.values.items.3.description": "Robust policies ensuring every student feels secure and supported.",
  "pages.about.values.items.3.title": "Safeguarding",
  "pages.about.values.overline": "What guides us",
  "pages.about.values.title": "Our values",
  "pages.joinus.hero.overline": "About Us",
  "pages.joinus.hero.subtitle": "Teaching, creative and operational opportunities at County Hall Dance Centre.",
  "pages.joinus.hero.title": "Join Us",
  "pages.joinus.intro": "We are building a welcoming creative community on the South Bank. Expressions of interest from teachers, artists and collaborators are welcome.",
  "pages.joinus.meta.description": "Join the team at County Hall Dance Centre.",
  "pages.joinus.meta.title": "Join Us",
  "pages.joinus.sections.apply.title": "How to apply",
  "pages.joinus.sections.opportunities.title": "Opportunities",
  "pages.events.categories.cross_arts_events.hero.overline": "Events",
  "pages.events.categories.cross_arts_events.hero.subtitle": "Where dance meets music, visual art and international cultural exchange.",
  "pages.events.categories.cross_arts_events.hero.title": "Cross-Arts Events",
  "pages.events.categories.cross_arts_events.intro": "Our Dance Meets Arts programme brings together movement, live music, visual art and cultural celebration.",
  "pages.events.categories.cross_arts_events.meta.description": "Dance Meets Arts cross-disciplinary events at County Hall Dance Centre.",
  "pages.events.categories.cross_arts_events.meta.title": "Cross-Arts Events",
  "pages.events.categories.cross_arts_events.sections.programme.title": "Programme",
  "pages.events.categories.cross_arts_events.sections.upcoming.title": "Upcoming events",
  "pages.events.categories.masterclasses.hero.overline": "Events",
  "pages.events.categories.masterclasses.hero.subtitle": "Learn from visiting artists and specialists in intimate studio settings.",
  "pages.events.categories.masterclasses.hero.title": "Masterclasses",
  "pages.events.categories.masterclasses.intro": "Masterclasses bring professional artists to County Hall for intensive teaching sessions across styles and levels.",
  "pages.events.categories.masterclasses.meta.description": "Guest artist masterclasses at County Hall Dance Centre.",
  "pages.events.categories.masterclasses.meta.title": "Masterclasses",
  "pages.events.categories.masterclasses.sections.levels.title": "Levels & requirements",
  "pages.events.categories.masterclasses.sections.upcoming.title": "Upcoming masterclasses",
  "pages.events.categories.milonga.hero.overline": "Events",
  "pages.events.categories.milonga.hero.subtitle": "Social tango evenings with live and recorded music in our South Bank studio.",
  "pages.events.categories.milonga.hero.title": "Milonga",
  "pages.events.categories.milonga.intro": "Join us for regular milongas — welcoming social dance nights for tango dancers of every level.",
  "pages.events.categories.milonga.meta.description": "Tango milonga social dance events at County Hall Dance Centre.",
  "pages.events.categories.milonga.meta.title": "Milonga",
  "pages.events.categories.milonga.sections.upcoming.title": "Upcoming milongas",
  "pages.events.categories.milonga.sections.what_to_expect.title": "What to expect",
  "pages.events.categories.performances.hero.overline": "Events",
  "pages.events.categories.performances.hero.subtitle": "Ticketed showcases, sharings and performance events throughout the year.",
  "pages.events.categories.performances.hero.title": "Performances",
  "pages.events.categories.performances.intro": "Celebrate the work of our community in performances ranging from informal sharings to ticketed showcase evenings.",
  "pages.events.categories.performances.meta.description": "Performances and showcases at County Hall Dance Centre.",
  "pages.events.categories.performances.meta.title": "Performances",
  "pages.events.categories.performances.sections.tickets.title": "Tickets",
  "pages.events.categories.performances.sections.upcoming.title": "Upcoming performances",
  "pages.events.categories.social_dance_nights.hero.overline": "Events",
  "pages.events.categories.social_dance_nights.hero.subtitle": "Themed evenings celebrating dance styles, music and community.",
  "pages.events.categories.social_dance_nights.hero.title": "Social Dance Nights",
  "pages.events.categories.social_dance_nights.intro": "From salsa socials to cross-style celebrations, our social nights are open to adults who love to move and connect.",
  "pages.events.categories.social_dance_nights.meta.description": "Themed social dance evenings at County Hall Dance Centre.",
  "pages.events.categories.social_dance_nights.meta.title": "Social Dance Nights",
  "pages.events.categories.social_dance_nights.sections.how_to_join.title": "How to join",
  "pages.events.categories.social_dance_nights.sections.upcoming.title": "Upcoming social nights",
  "pages.events.categories.workshops.hero.overline": "Events",
  "pages.events.categories.workshops.hero.subtitle": "One-off intensives and taster sessions with guest artists and faculty.",
  "pages.events.categories.workshops.hero.title": "Workshops",
  "pages.events.categories.workshops.intro": "Workshops offer a focused opportunity to explore a style, technique or theme in a single session or short series.",
  "pages.events.categories.workshops.meta.description": "Dance and movement workshops at County Hall Dance Centre.",
  "pages.events.categories.workshops.meta.title": "Workshops",
  "pages.events.categories.workshops.sections.booking.title": "Booking",
  "pages.events.categories.workshops.sections.upcoming.title": "Upcoming workshops",
  "pages.events.categorylabels.backlink": "← All events",
  "pages.events.detaillabels.backlink": "← All events",
  "pages.events.detaillabels.date": "Date",
  "pages.events.detaillabels.location": "Location",
  "pages.events.hero.overline": "What's on",
  "pages.events.hero.subtitle": "One-off workshops, guest artist intensives, and ticketed performances throughout the year.",
  "pages.events.hero.title": "Events & Masterclasses",
  "pages.events.intro": "Book directly via the links below. Event payments are processed securely through Stripe — class bookings remain on our timetable system.",
  "pages.events.items.contemporary_intensive_maya_chen.booknow.label": "Book Now",
  "pages.events.items.contemporary_intensive_maya_chen.date": "Saturday 18 October 2026",
  "pages.events.items.contemporary_intensive_maya_chen.description.0": "Join internationally recognised choreographer Maya Chen for a day of contemporary training at intermediate level and above.",
  "pages.events.items.contemporary_intensive_maya_chen.description.1": "The morning focuses on floor work and release principles; the afternoon introduces excerpts from Maya's touring repertory.",
  "pages.events.items.contemporary_intensive_maya_chen.description.2": "Please bring knee pads and water. Places are limited to 24 participants.",
  "pages.events.items.contemporary_intensive_maya_chen.excerpt": "A full-day intensive exploring release technique and repertory with guest artist Maya Chen.",
  "pages.events.items.contemporary_intensive_maya_chen.image.alt": "Contemporary dance intensive workshop",
  "pages.events.items.contemporary_intensive_maya_chen.location": "Studio A",
  "pages.events.items.contemporary_intensive_maya_chen.title": "Contemporary Intensive with Maya Chen",
  "pages.events.items.junior_ballet_masterclass.booknow.label": "Book Now",
  "pages.events.items.junior_ballet_masterclass.date": "Sunday 26 October 2026",
  "pages.events.items.junior_ballet_masterclass.description.0": "Led by a guest RAD examiner, this masterclass refines alignment, épaulement, and petite allegro.",
  "pages.events.items.junior_ballet_masterclass.description.1": "Suitable for students currently studying Grade 2–4 or equivalent.",
  "pages.events.items.junior_ballet_masterclass.excerpt": "A special masterclass for junior ballet students aged 8–12.",
  "pages.events.items.junior_ballet_masterclass.image.alt": "Junior ballet masterclass in progress",
  "pages.events.items.junior_ballet_masterclass.location": "Studio B",
  "pages.events.items.junior_ballet_masterclass.title": "Junior Ballet Masterclass",
  "pages.events.items.musical_theatre_workshop_day.booknow.label": "Book Now",
  "pages.events.items.musical_theatre_workshop_day.date": "Saturday 8 November 2026",
  "pages.events.items.musical_theatre_workshop_day.description.0": "A lively day of triple-threat training, ending with a short sharing for friends and family.",
  "pages.events.items.musical_theatre_workshop_day.description.1": "Open to ages 10–16 with some prior dance or drama experience recommended.",
  "pages.events.items.musical_theatre_workshop_day.excerpt": "Sing, dance, and act through a full musical theatre workshop day.",
  "pages.events.items.musical_theatre_workshop_day.image.alt": "Musical theatre workshop participants on stage",
  "pages.events.items.musical_theatre_workshop_day.location": "Main Hall",
  "pages.events.items.musical_theatre_workshop_day.title": "Musical Theatre Workshop Day",
  "pages.events.items.winter_showcase.booknow.label": "Book Now",
  "pages.events.items.winter_showcase.date": "Friday 12 December 2026",
  "pages.events.items.winter_showcase.description.0": "Celebrate the talent of the CHD PAS community in an evening of ballet, contemporary, jazz, and musical theatre.",
  "pages.events.items.winter_showcase.description.1": "Doors open at 18:30; performance begins at 19:00. Running time approximately 90 minutes including interval.",
  "pages.events.items.winter_showcase.excerpt": "Our annual winter showcase featuring students from every discipline.",
  "pages.events.items.winter_showcase.image.alt": "Winter showcase performance lighting",
  "pages.events.items.winter_showcase.location": "County Hall Theatre",
  "pages.events.items.winter_showcase.title": "Winter Showcase — Tickets On Sale",
  "pages.events.meta.description": "Masterclasses, workshops, and performances at County Hall Dance & Performing Arts School.",
  "pages.events.meta.title": "Events & Masterclasses",
  "pages.booking.form.description": "Tell us what you are looking for — studio hire, class booking, membership or a general question.",
  "pages.booking.form.fields.email_address.label": "Email address",
  "pages.booking.form.fields.email_address.placeholder": "you@example.com",
  "pages.booking.form.fields.enquiry_about.label": "Enquiry about",
  "pages.booking.form.fields.enquiry_about.options.classes_booking.label": "Classes Booking",
  "pages.booking.form.fields.enquiry_about.options.general_enquire.label": "General Enquire",
  "pages.booking.form.fields.enquiry_about.options.membership_booking.label": "Membership Booking",
  "pages.booking.form.fields.enquiry_about.options.studio_hire.label": "Studio Hire",
  "pages.booking.form.fields.full_name.label": "Full name",
  "pages.booking.form.fields.full_name.placeholder": "Your name",
  "pages.booking.form.fields.message.label": "Message",
  "pages.booking.form.fields.message.placeholder": "Please include any relevant details — dates, class names, group size, etc.",
  "pages.booking.form.fields.phone_optional.label": "Phone (optional)",
  "pages.booking.form.fields.phone_optional.placeholder": "+44 …",
  "pages.booking.form.selectplaceholder": "Select an option",
  "pages.booking.form.submitlabel": "Send message",
  "pages.booking.form.successmessage": "Thank you — your enquiry has been received. We will be in touch shortly.",
  "pages.booking.form.title": "Send an enquiry",
  "pages.booking.hero.overline": "We'd love to hear from you",
  "pages.booking.hero.subtitle": "Complete the form below and our team will respond by email within two working days.",
  "pages.booking.hero.title": "Booking & Enquiries",
  "pages.booking.meta.description": "Send a booking or general enquiry to County Hall Dance Centre — studio hire, classes, membership and more.",
  "pages.booking.meta.title": "Booking & Enquiries",
  "pages.contact.details.address.0": "County Hall Dance Studio",
  "pages.contact.details.address.1": "Belvedere Road",
  "pages.contact.details.address.2": "London SE1 7GP",
  "pages.contact.details.email": "hello@countyhalldance.co.uk",
  "pages.contact.details.hours": "Office hours: Mon – Fri, 9:00 – 17:30",
  "pages.contact.details.phone": "+44 20 7946 0958",
  "pages.contact.details.title": "Studio details",
  "pages.contact.form.description": "Complete the form below and we will respond within two working days.",
  "pages.contact.form.fields.email_address.label": "Email address",
  "pages.contact.form.fields.email_address.placeholder": "you@example.com",
  "pages.contact.form.fields.full_name.label": "Full name",
  "pages.contact.form.fields.full_name.placeholder": "Your name",
  "pages.contact.form.fields.message.label": "Message",
  "pages.contact.form.fields.message.placeholder": "How can we help?",
  "pages.contact.form.fields.phone_optional.label": "Phone (optional)",
  "pages.contact.form.fields.phone_optional.placeholder": "+44 …",
  "pages.contact.form.fields.subject.label": "Subject",
  "pages.contact.form.fields.subject.options.classes_timetable.label": "Classes & timetable",
  "pages.contact.form.fields.subject.options.courses.label": "Courses",
  "pages.contact.form.fields.subject.options.general_enquiry.label": "General enquiry",
  "pages.contact.form.fields.subject.options.gift_cards.label": "Gift cards",
  "pages.contact.form.fields.subject.options.private_events.label": "Private events",
  "pages.contact.form.selectplaceholder": "Select an option",
  "pages.contact.form.submitlabel": "Send message",
  "pages.contact.form.successmessage": "Thank you — your message has been received. We will be in touch shortly.",
  "pages.contact.form.title": "Send an enquiry",
  "pages.contact.hero.overline": "We'd love to hear from you",
  "pages.contact.hero.subtitle": "Questions about classes, courses, private events, or anything else — send us a message.",
  "pages.contact.hero.title": "Contact",
  "pages.contact.map.directionslabel": "Open in Google Maps →",
  "pages.contact.map.title": "Find us",
  "pages.contact.meta.description": "Get in touch with County Hall Dance & Performing Arts School.",
  "pages.contact.meta.title": "Contact",
  "pages.faq.cta.button.label": "Contact us",
  "pages.faq.cta.text": "Can't find what you need?",
  "pages.faq.hero.overline": "Help centre",
  "pages.faq.hero.subtitle": "Quick answers to common questions. Still unsure? Contact our friendly team.",
  "pages.faq.hero.title": "Frequently asked questions",
  "pages.faq.items.faq_1.answer": "Visit our Timetable & Booking page and use the booking widget to select a class. You will be directed to our external booking partner to complete registration and payment.",
  "pages.faq.items.faq_1.question": "How do I book a class?",
  "pages.faq.items.faq_2.answer": "Yes. We offer a complimentary trial for new students on selected classes. Choose the trial option when booking through the timetable.",
  "pages.faq.items.faq_2.question": "Can my child try a class before committing?",
  "pages.faq.items.faq_3.answer": "Comfortable activewear is fine for a trial. If they continue, we will provide a uniform list — typically leotard, tights, ballet shoes, and hair in a neat bun.",
  "pages.faq.items.faq_3.question": "What should my child wear to their first ballet class?",
  "pages.faq.items.faq_4.answer": "Courses run for a fixed term with a structured syllabus and limited places. Regular classes can often be booked on a rolling basis via the timetable.",
  "pages.faq.items.faq_4.question": "How are courses different from regular classes?",
  "pages.faq.items.faq_5.answer": "Optional examinations are available in ballet, tap, and drama through recognised awarding bodies. Your child's teacher will advise when they are ready.",
  "pages.faq.items.faq_5.question": "Do you offer exams?",
  "pages.faq.items.faq_6.answer": "Events are booked directly via the Book Now button on each event page. Payments are processed securely through Stripe.",
  "pages.faq.items.faq_6.question": "How do I book an event or masterclass?",
  "pages.faq.items.faq_7.answer": "There is limited on-site parking by arrangement. We recommend public transport — Waterloo station is a short walk from County Hall.",
  "pages.faq.items.faq_7.question": "Is there parking nearby?",
  "pages.faq.meta.description": "Frequently asked questions about classes, courses, and bookings at CHD PAS.",
  "pages.faq.meta.title": "FAQ",
  "pages.giftcards.hero.overline": "A thoughtful gift",
  "pages.giftcards.hero.subtitle": "Perfect for birthdays, holidays, or encouraging someone to take their first class.",
  "pages.giftcards.hero.title": "Gift Cards",
  "pages.giftcards.intro": "Gift cards can be redeemed against classes, courses, workshops, and merchandise. They are delivered by email and valid for twelve months from purchase.",
  "pages.giftcards.meta.description": "Give the gift of dance with a CHD PAS gift card.",
  "pages.giftcards.meta.title": "Gift Cards",
  "pages.giftcards.options.gift_100.amount": "£100",
  "pages.giftcards.options.gift_100.cta.label": "Buy £100 card",
  "pages.giftcards.options.gift_100.description": "A generous gift towards a full course or multiple masterclasses.",
  "pages.giftcards.options.gift_100.title": "£100 Gift Card",
  "pages.giftcards.options.gift_25.amount": "£25",
  "pages.giftcards.options.gift_25.cta.label": "Buy £25 card",
  "pages.giftcards.options.gift_25.description": "Ideal for a single workshop or as a contribution towards term fees.",
  "pages.giftcards.options.gift_25.title": "£25 Gift Card",
  "pages.giftcards.options.gift_50.amount": "£50",
  "pages.giftcards.options.gift_50.cta.label": "Buy £50 card",
  "pages.giftcards.options.gift_50.description": "Covers several drop-in classes or part of a term enrolment.",
  "pages.giftcards.options.gift_50.title": "£50 Gift Card",
  "pages.giftcards.terms": "Gift cards are non-refundable and cannot be exchanged for cash. Remaining balances stay on the card until used. Contact us for custom amounts.",
  "ui.booking.orcall": "or call",
  "ui.booking.preferdirectprefix": "Prefer to reach us directly? Email",
  "ui.form.requiredmarker": " *",
  "ui.header.closemenu": "Close menu",
  "ui.header.mainnavigation": "Main navigation",
  "ui.header.mobilenavigation": "Mobile navigation",
  "ui.header.openmenu": "Open menu",
  "ui.header.submenusuffix": " submenu",
  "ui.hero.featuredhighlights": "Featured highlights",
  "ui.hero.slidenavigation": "Slide navigation",
  "ui.hero.slideprefix": "Slide",
  "ui.sectionedpage.comingsoon": "Content for this section is coming soon."
} as const;

export type CopyId = keyof typeof copy;
