import type { TesterClass } from "@/lib/tester-classes/types";
import { DEFAULT_BOOKING_URL } from "@/lib/tester-classes/types";

/** Fallback data when Airtable is not configured. Matches the five live classes. */
export const SEED_CLASSES: TesterClass[] = [
  {
    id: "seed-sound-healing-yoga",
    title: "Sound Healing Yoga",
    day: "Tue",
    startTime: "12:30 pm",
    endTime: "1:25 pm",
    dateRange: "Sept – Sept 2026",
    ageGroup: "Any age",
    location: "County Hall Dance Centre",
    price: 10,
    discipline: "Sound Healing",
    imageUrl: "/images/hero/slide-3.jpg",
    bookingUrl: DEFAULT_BOOKING_URL,
  },
  {
    id: "seed-tai-chi",
    title: "Tai Chi",
    day: "Tue",
    startTime: "6:30 pm",
    endTime: "7:30 pm",
    dateRange: "Sept – Sept 2026",
    ageGroup: "Any age",
    location: "County Hall Dance Centre",
    price: 10,
    discipline: "Tai Chi",
    imageUrl: "/images/hero/slide-6.jpg",
    bookingUrl: DEFAULT_BOOKING_URL,
  },
  {
    id: "seed-contemporary",
    title: "Contemporary Dance",
    day: "Tue",
    startTime: "7:30 pm",
    endTime: "8:30 pm",
    dateRange: "Sept – Sept 2026",
    ageGroup: "Any age",
    location: "County Hall Dance Centre",
    price: 10,
    discipline: "Contemporary",
    imageUrl: "/images/hero/slide-1.jpg",
    bookingUrl: DEFAULT_BOOKING_URL,
  },
  {
    id: "seed-yoga",
    title: "Yoga (Basic Flow)",
    day: "Wed",
    startTime: "6:30 pm",
    endTime: "7:20 pm",
    dateRange: "Sept – Sept 2026",
    ageGroup: "Any age",
    location: "County Hall Dance Centre",
    price: 10,
    discipline: "Yoga",
    imageUrl: "/images/hero/slide-5.jpg",
    bookingUrl: DEFAULT_BOOKING_URL,
  },
  {
    id: "seed-tango",
    title: "Argentine Tango (Beginner)",
    day: "Wed",
    startTime: "7:30 pm",
    endTime: "8:30 pm",
    dateRange: "Sept – Sept 2026",
    ageGroup: "Any age",
    location: "County Hall Dance Centre",
    price: 10,
    discipline: "Tango",
    level: "Beginner",
    imageUrl: "/images/hero/slide-2.jpg",
    bookingUrl: DEFAULT_BOOKING_URL,
  },
];
